<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapitel 5 Binära variabler | Tillämpad statistik med R</title>
  <meta name="description" content="Kapitel 5 Binära variabler | Tillämpad statistik med R" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapitel 5 Binära variabler | Tillämpad statistik med R" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapitel 5 Binära variabler | Tillämpad statistik med R" />
  
  
  

<meta name="author" content="Ronnie Pingel och Valentin Zulj" />


<meta name="date" content="2020-11-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="läsa-in-och-spara-data.html"/>
<link rel="next" href="kategorivariabler-uppdateras.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduktion</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#om-statistisk-programmering-med-r"><i class="fa fa-check"></i><b>1.1</b> Om statistisk programmering med R</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#allmänna-tips-om-r-på-kursen"><i class="fa fa-check"></i><b>1.2</b> Allmänna tips om R på kursen</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#sammanfattning"><i class="fa fa-check"></i><b>1.3</b> Sammanfattning</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#referenser"><i class="fa fa-check"></i><b>1.4</b> Referenser</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html"><i class="fa fa-check"></i><b>2</b> Att börja använda R</a><ul>
<li class="chapter" data-level="2.1" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#installation-av-r-och-rstudio"><i class="fa fa-check"></i><b>2.1</b> Installation av R och RStudio</a><ul>
<li class="chapter" data-level="2.1.1" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#installation-av-r-på-macos"><i class="fa fa-check"></i><b>2.1.1</b> Installation av R på MacOS</a></li>
<li class="chapter" data-level="2.1.2" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#installation-av-r-på-windows"><i class="fa fa-check"></i><b>2.1.2</b> Installation av R på Windows</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#installation-av-rstudio"><i class="fa fa-check"></i><b>2.2</b> Installation av RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#första-sessionen"><i class="fa fa-check"></i><b>2.3</b> Första sessionen</a></li>
<li class="chapter" data-level="2.4" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#paket"><i class="fa fa-check"></i><b>2.4</b> Paket</a></li>
<li class="chapter" data-level="2.5" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#sammanfattning-1"><i class="fa fa-check"></i><b>2.5</b> Sammanfattning</a></li>
<li class="chapter" data-level="2.6" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övningar"><i class="fa fa-check"></i><b>2.6</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.1"><i class="fa fa-check"></i>Övning 2.1</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.2"><i class="fa fa-check"></i>Övning 2.2</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.3"><i class="fa fa-check"></i>Övning 2.3</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.4"><i class="fa fa-check"></i>Övning 2.4</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.5"><i class="fa fa-check"></i>Övning 2.5</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.6"><i class="fa fa-check"></i>Övning 2.6</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.7"><i class="fa fa-check"></i>Övning 2.7</a></li>
<li class="chapter" data-level="" data-path="att-börja-använda-r.html"><a href="att-börja-använda-r.html#övning-2.8"><i class="fa fa-check"></i>Övning 2.8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html"><i class="fa fa-check"></i><b>3</b> Data, objekt och funktioner</a><ul>
<li class="chapter" data-level="3.1" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#data-och-objekt"><i class="fa fa-check"></i><b>3.1</b> Data och objekt</a></li>
<li class="chapter" data-level="3.2" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#vektorer"><i class="fa fa-check"></i><b>3.2</b> Vektorer</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#vektorer-och-indexering"><i class="fa fa-check"></i><b>3.2.1</b> Vektorer och indexering</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#vektorer-och-logiska-operatorer"><i class="fa fa-check"></i><b>3.2.2</b> Vektorer och logiska operatorer</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#matriser"><i class="fa fa-check"></i><b>3.3</b> Matriser</a></li>
<li class="chapter" data-level="3.4" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data frames</a></li>
<li class="chapter" data-level="3.5" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#funktioner"><i class="fa fa-check"></i><b>3.5</b> Funktioner</a></li>
<li class="chapter" data-level="3.6" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#sammanfattning-2"><i class="fa fa-check"></i><b>3.6</b> Sammanfattning</a></li>
<li class="chapter" data-level="3.7" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övningar-1"><i class="fa fa-check"></i><b>3.7</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.1"><i class="fa fa-check"></i>Övning 3.1</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.2"><i class="fa fa-check"></i>Övning 3.2</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.3"><i class="fa fa-check"></i>Övning 3.3</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.4"><i class="fa fa-check"></i>Övning 3.4</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.5"><i class="fa fa-check"></i>Övning 3.5</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.6"><i class="fa fa-check"></i>Övning 3.6</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.7"><i class="fa fa-check"></i>Övning 3.7</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.8"><i class="fa fa-check"></i>Övning 3.8</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.9"><i class="fa fa-check"></i>Övning 3.9</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.10"><i class="fa fa-check"></i>Övning 3.10</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.11"><i class="fa fa-check"></i>Övning 3.11</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.12"><i class="fa fa-check"></i>Övning 3.12</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.13"><i class="fa fa-check"></i>Övning 3.13</a></li>
<li class="chapter" data-level="" data-path="data-objekt-och-funktioner.html"><a href="data-objekt-och-funktioner.html#övning-3.14"><i class="fa fa-check"></i>Övning 3.14</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html"><i class="fa fa-check"></i><b>4</b> Läsa in och spara data</a><ul>
<li class="chapter" data-level="4.1" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#principer-för-organiserade-datamaterial"><i class="fa fa-check"></i><b>4.1</b> Principer för organiserade datamaterial</a></li>
<li class="chapter" data-level="4.2" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#working-directory"><i class="fa fa-check"></i><b>4.2</b> Working directory</a></li>
<li class="chapter" data-level="4.3" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#läsa-in-datamaterial-med-hjälp-av-kod"><i class="fa fa-check"></i><b>4.3</b> Läsa in datamaterial med hjälp av kod</a><ul>
<li class="chapter" data-level="4.3.1" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#text--och-csv-filer"><i class="fa fa-check"></i><b>4.3.1</b> Text- och CSV-filer</a></li>
<li class="chapter" data-level="4.3.2" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#excel-filer"><i class="fa fa-check"></i><b>4.3.2</b> Excel-filer</a></li>
<li class="chapter" data-level="4.3.3" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#övriga-format"><i class="fa fa-check"></i><b>4.3.3</b> Övriga format</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#läsa-in-datamaterial-med-hjälp-av-menyerna-i-rstudio"><i class="fa fa-check"></i><b>4.4</b> Läsa in datamaterial med hjälp av menyerna i RStudio</a><ul>
<li class="chapter" data-level="4.4.1" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#läsa-in-data-från-working-directory"><i class="fa fa-check"></i><b>4.4.1</b> Läsa in data från working directory</a></li>
<li class="chapter" data-level="4.4.2" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#läsa-in-data-med-import-dataset"><i class="fa fa-check"></i><b>4.4.2</b> Läsa in data med “Import Dataset”</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#spara-datamaterial-med-hjälp-av-r"><i class="fa fa-check"></i><b>4.5</b> Spara datamaterial med hjälp av R</a></li>
<li class="chapter" data-level="4.6" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#övningar-2"><i class="fa fa-check"></i><b>4.6</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#övning-4.1"><i class="fa fa-check"></i>Övning 4.1</a></li>
<li class="chapter" data-level="" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#övning-4.2"><i class="fa fa-check"></i>Övning 4.2</a></li>
<li class="chapter" data-level="" data-path="läsa-in-och-spara-data.html"><a href="läsa-in-och-spara-data.html#övning-4.3"><i class="fa fa-check"></i>Övning 4.3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="binära-variabler.html"><a href="binära-variabler.html"><i class="fa fa-check"></i><b>5</b> Binära variabler</a><ul>
<li class="chapter" data-level="5.1" data-path="binära-variabler.html"><a href="binära-variabler.html#deskription-av-en-binär-variabel"><i class="fa fa-check"></i><b>5.1</b> Deskription av en binär variabel</a></li>
<li class="chapter" data-level="5.2" data-path="binära-variabler.html"><a href="binära-variabler.html#tabeller-och-en-binär-variabel"><i class="fa fa-check"></i><b>5.2</b> Tabeller och en binär variabel</a></li>
<li class="chapter" data-level="5.3" data-path="binära-variabler.html"><a href="binära-variabler.html#figurer-och-en-binär-variabel"><i class="fa fa-check"></i><b>5.3</b> Figurer och en binär variabel</a></li>
<li class="chapter" data-level="5.4" data-path="binära-variabler.html"><a href="binära-variabler.html#inferens-för-binär-variabel"><i class="fa fa-check"></i><b>5.4</b> Inferens för binär variabel</a></li>
<li class="chapter" data-level="5.5" data-path="binära-variabler.html"><a href="binära-variabler.html#deskription-av-två-binära-variabler"><i class="fa fa-check"></i><b>5.5</b> Deskription av två binära variabler</a></li>
<li class="chapter" data-level="5.6" data-path="binära-variabler.html"><a href="binära-variabler.html#tabeller-och-två-binära-variabler"><i class="fa fa-check"></i><b>5.6</b> Tabeller och två binära variabler</a></li>
<li class="chapter" data-level="5.7" data-path="binära-variabler.html"><a href="binära-variabler.html#kvantifiering-av-samband-mellan-två-binära-variabler"><i class="fa fa-check"></i><b>5.7</b> Kvantifiering av samband mellan två binära variabler</a></li>
<li class="chapter" data-level="5.8" data-path="binära-variabler.html"><a href="binära-variabler.html#figurer-och-två-binära-variabler"><i class="fa fa-check"></i><b>5.8</b> Figurer och två binära variabler</a></li>
<li class="chapter" data-level="5.9" data-path="binära-variabler.html"><a href="binära-variabler.html#inferens-för-två-binära-variabler"><i class="fa fa-check"></i><b>5.9</b> Inferens för två binära variabler</a></li>
<li class="chapter" data-level="5.10" data-path="binära-variabler.html"><a href="binära-variabler.html#övningar-3"><i class="fa fa-check"></i><b>5.10</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.1"><i class="fa fa-check"></i>Övning 5.1</a></li>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.2"><i class="fa fa-check"></i>Övning 5.2</a></li>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.3"><i class="fa fa-check"></i>Övning 5.3</a></li>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.4"><i class="fa fa-check"></i>Övning 5.4</a></li>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.5"><i class="fa fa-check"></i>Övning 5.5</a></li>
<li class="chapter" data-level="" data-path="binära-variabler.html"><a href="binära-variabler.html#övning-5.6"><i class="fa fa-check"></i>Övning 5.6</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="binära-variabler.html"><a href="binära-variabler.html#referenser-1"><i class="fa fa-check"></i><b>5.11</b> Referenser</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html"><i class="fa fa-check"></i><b>6</b> Kategorivariabler (uppdateras)</a><ul>
<li class="chapter" data-level="6.1" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#deskription-av-en-variabel-med-fler-än-två-kategorier"><i class="fa fa-check"></i><b>6.1</b> Deskription av en variabel med fler än två kategorier</a></li>
<li class="chapter" data-level="6.2" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#figurer-och-en-kategorivariabel-med-fler-än-2-kategorier"><i class="fa fa-check"></i><b>6.2</b> Figurer och en kategorivariabel med fler än 2 kategorier</a></li>
<li class="chapter" data-level="6.3" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#inferens-och-en-kategorivariabel-med-fler-än-2-kategorier"><i class="fa fa-check"></i><b>6.3</b> Inferens och en kategorivariabel med fler än 2 kategorier</a></li>
<li class="chapter" data-level="6.4" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övningar-4"><i class="fa fa-check"></i><b>6.4</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.1"><i class="fa fa-check"></i>Övning 6.1</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.2"><i class="fa fa-check"></i>Övning 6.2</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.3"><i class="fa fa-check"></i>Övning 6.3</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.4"><i class="fa fa-check"></i>Övning 6.4</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.5"><i class="fa fa-check"></i>Övning 6.5</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.6"><i class="fa fa-check"></i>Övning 6.6</a></li>
<li class="chapter" data-level="" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#övning-6.7"><i class="fa fa-check"></i>Övning 6.7</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="kategorivariabler-uppdateras.html"><a href="kategorivariabler-uppdateras.html#referenser-2"><i class="fa fa-check"></i><b>6.5</b> Referenser</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html"><i class="fa fa-check"></i><b>7</b> Urvalsmetoder</a><ul>
<li class="chapter" data-level="7.1" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#obundet-slumpmässigt-urval-utan-återläggning"><i class="fa fa-check"></i><b>7.1</b> Obundet slumpmässigt urval utan återläggning</a><ul>
<li class="chapter" data-level="7.1.1" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-populationsmedelvärdet-mu"><i class="fa fa-check"></i><b>7.1.1</b> Inferens för populationsmedelvärdet, <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="7.1.2" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-populationsandelen-p"><i class="fa fa-check"></i><b>7.1.2</b> Inferens för populationsandelen, <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="7.1.3" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-populationstotalen-tau"><i class="fa fa-check"></i><b>7.1.3</b> Inferens för populationstotalen, <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="7.1.4" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#beräkningar-av-stickprovstorlek"><i class="fa fa-check"></i><b>7.1.4</b> Beräkningar av stickprovstorlek</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#stratifierat-urval"><i class="fa fa-check"></i><b>7.2</b> Stratifierat urval</a><ul>
<li class="chapter" data-level="7.2.1" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-mu"><i class="fa fa-check"></i><b>7.2.1</b> Inferens för <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="7.2.2" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-p"><i class="fa fa-check"></i><b>7.2.2</b> Inferens för <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="7.2.3" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-tau"><i class="fa fa-check"></i><b>7.2.3</b> Inferens för <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="7.2.4" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#allokering-av-n"><i class="fa fa-check"></i><b>7.2.4</b> Allokering av <span class="math inline">\(n\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#gruppurval"><i class="fa fa-check"></i><b>7.3</b> Gruppurval</a><ul>
<li class="chapter" data-level="7.3.1" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-mu-1"><i class="fa fa-check"></i><b>7.3.1</b> Inferens för <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="7.3.2" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-tau-1"><i class="fa fa-check"></i><b>7.3.2</b> Inferens för <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="7.3.3" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#inferens-för-p-1"><i class="fa fa-check"></i><b>7.3.3</b> Inferens för <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#efterstratifiering"><i class="fa fa-check"></i><b>7.4</b> Efterstratifiering</a></li>
<li class="chapter" data-level="7.5" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övningar-5"><i class="fa fa-check"></i><b>7.5</b> Övningar</a><ul>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.1"><i class="fa fa-check"></i>Övning 7.1</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.2"><i class="fa fa-check"></i>Övning 7.2</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.3"><i class="fa fa-check"></i>Övning 7.3</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.4"><i class="fa fa-check"></i>Övning 7.4</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.5"><i class="fa fa-check"></i>Övning 7.5</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.6"><i class="fa fa-check"></i>Övning 7.6</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.7"><i class="fa fa-check"></i>Övning 7.7</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.8"><i class="fa fa-check"></i>Övning 7.8</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.9"><i class="fa fa-check"></i>Övning 7.9</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.10"><i class="fa fa-check"></i>Övning 7.10</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.11"><i class="fa fa-check"></i>Övning 7.11</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.12"><i class="fa fa-check"></i>Övning 7.12</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.13"><i class="fa fa-check"></i>Övning 7.13</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.14"><i class="fa fa-check"></i>Övning 7.14</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.15"><i class="fa fa-check"></i>Övning 7.15</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.16"><i class="fa fa-check"></i>Övning 7.16</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.16-1"><i class="fa fa-check"></i>Övning 7.16</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.17"><i class="fa fa-check"></i>Övning 7.17</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.18"><i class="fa fa-check"></i>Övning 7.18</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.19"><i class="fa fa-check"></i>Övning 7.19</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.20"><i class="fa fa-check"></i>Övning 7.20</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.21"><i class="fa fa-check"></i>Övning 7.21</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.22"><i class="fa fa-check"></i>Övning 7.22</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.23"><i class="fa fa-check"></i>Övning 7.23</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.24"><i class="fa fa-check"></i>Övning 7.24</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.25"><i class="fa fa-check"></i>Övning 7.25</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.26"><i class="fa fa-check"></i>Övning 7.26</a></li>
<li class="chapter" data-level="" data-path="urvalsmetoder.html"><a href="urvalsmetoder.html#övning-7.27"><i class="fa fa-check"></i>Övning 7.27</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tillämpad statistik med R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="binära-variabler" class="section level1">
<h1><span class="header-section-number">Kapitel 5</span> Binära variabler</h1>
<p>En nödvändig färdighet vid arbete med data är att kunna hantera och analysera kategorivariabler. Vi börjar i detta kapitel med det enkla fallet binära variabler för att i ett senare kapitel övergå till att studera hur man arbetar med variabler som har fler än två kategorier.</p>
<div id="deskription-av-en-binär-variabel" class="section level2">
<h2><span class="header-section-number">5.1</span> Deskription av en binär variabel</h2>
<p>Detta avsnitt fokuserar på analys av <strong>binära</strong> kategorivariabler. I princip alla datamaterial innehåller variabler med två kategorier och även om data inledningsvis inte innehåller binära variabler är det vanligt att av olika skäl omkoda kvantitativa variabler till variabler med två kategorier. För nybörjaren kan det vara förvirrande att det finns åtminstone två alternativ, som bägge är viktiga, för hur man arbetar med binära variabler.</p>
<ul>
<li><strong>Alternativ 1</strong>. En binär kategorivariabel hanteras som en numerisk variabel efter att kategorierna tilldelats numeriska värden. Exempelvis kan vi ange att värdena 0 och 1 representerar två kategorier. Observera att val värden påverkar hur variabeln används i analysen.</li>
<li><strong>Alternativ 2</strong>. En binär kategoriabel definieras med funktionen <strong>factor()</strong>som datatypen <strong>faktor</strong>. En faktors kategorier benämns i R för <strong>levels</strong> (nivåer). Fördelen med att definiera en variabel som faktor är att R kan använda information om den binära variabeln i analyser och resultat. Till exempel kan kategoriernas namn presenteras i resultat. Dessutom kräver en del metoder i R en faktor-variabel. Observera att det, av förklarliga skäl, inte går att utföra räkneoperationer på variabler definierade som datatypen faktor.</li>
</ul>
<p>Eftersom bägge varianterna har för- och nackdelar återfinns ofta <strong>bägge varianter</strong> av kodning för en och samma binära variabel i ett dataset — en numerisk version kodad 0-1 kallad för <strong>variabelnamn_bin</strong> och version kodad som faktor kallad <strong>variabelnamn_cat</strong>.</p>
<p>Oavsett om en binär variabel har kategorier som inte går att rangordna (till exempel variabeln <span class="math inline">\(kön\)</span> med kategorierna <span class="math inline">\(kvinna\)</span> och <span class="math inline">\(man\)</span>) eller har kategorier som går att rangordna (till exempel <span class="math inline">\(utbildning\)</span> med kategorierna <span class="math inline">\(låg\)</span> och <span class="math inline">\(hög\)</span>) beskrivs en binär variabel på samma sätt. Vi ska nu presentera visa hur man beskriver en binär variabel, utifrån de tidigare två nämnda alternativen.</p>
<p>Vi exemplifierar med att beskriva variabel som heter <span class="math inline">\(education\)</span> som har två kategorier, <span class="math inline">\(low\)</span> och <span class="math inline">\(high\)</span> och som vi läser in nedan. Med funktionen <strong>str()</strong> identifieras att <span class="math inline">\(education\)</span> är en variabel med datatypen <em>character</em>. Det är alltid viktigt att undersöka variablers datatyp, emellertid är detta ingen kod som sedan sparas i scriptet. Efter datatypen är undersökt kan denna rad med kod tas bort från scriptet. Funktionen <strong>str()</strong> är användbar för att undersöka alla typer av objekt i R, till exempel variabler, dataframes och objekt som innehåller sparade resultat.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Ursprungsvariabel, data du har erhållit.</span>
  education &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>,  
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>,  
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>,  
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, 
               <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>,  
               <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>, <span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,
               <span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>,<span class="st">&quot;low&quot;</span>)
<span class="co"># Undersök hur R identifierar variabelns datatyp  </span>
  <span class="kw">str</span>(education)
<span class="op">&gt;</span><span class="st">  </span>chr [<span class="dv">1</span><span class="op">:</span><span class="dv">280</span>] <span class="st">&quot;high&quot;</span> <span class="st">&quot;high&quot;</span> <span class="st">&quot;low&quot;</span> <span class="st">&quot;high&quot;</span> <span class="st">&quot;high&quot;</span> <span class="st">&quot;low&quot;</span> <span class="st">&quot;high&quot;</span> <span class="st">&quot;low&quot;</span> ...</code></pre></div>
<p>Med <strong>Alternativ 1</strong> tilldelas de två kategorierna i den binära variabeln numeriska värden och variabeln analyseras sedan som en numerisk variabel. Det är vanligast att ge kategorierna värdena 0 och 1. En anledning är tolkningen blir i termer av andelar av den kategori som är kodad 1.</p>
<p>Exemplet nedan illustrerar hur man med det numeriska alternativet kan beskriva den ursprungliga variabeln <span class="math inline">\(education\)</span> som har kategorierna <span class="math inline">\(low\)</span> och <span class="math inline">\(high\)</span>. Den uppenbara fördelen med att kodningen 0-1, jämfört med 1-2, är att 0-1 ger en bekväm tolkning eftersom medelvärdet då är proportionen.</p>
<p>Kommandot <strong>str()</strong> identifierar nu att både <em>edu_bin</em> och <em>edu_12</em> är av typen <em>numeric</em>.</p>
<p>Med <strong>mean()</strong> och <strong>summary()</strong> erhålls information som beskriver <em>edu_bin</em> och <em>edu_12</em>. Vi ser att 41% har hög utbildning. Däremot ser vi inte hur många som har låg respektive hög utbildning.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Numerisk kodning: 0 = low, 1 = high</span>
  edu_bin &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, <span class="kw">length</span>(education))
  edu_bin[education <span class="op">==</span><span class="st"> &quot;high&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span>
  edu_bin[education <span class="op">==</span><span class="st"> &quot;low&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
  <span class="kw">str</span>(edu_bin)
<span class="op">&gt;</span><span class="st">  </span>num [<span class="dv">1</span><span class="op">:</span><span class="dv">280</span>] <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">1</span> ...
  phat &lt;-<span class="st"> </span><span class="kw">mean</span>(edu_bin)
  phat
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="fl">0.4142857</span>
  <span class="kw">summary</span>(edu_bin)
<span class="op">&gt;</span><span class="st">    </span>Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
<span class="op">&gt;</span><span class="st">  </span><span class="fl">0.0000</span>  <span class="fl">0.0000</span>  <span class="fl">0.0000</span>  <span class="fl">0.4143</span>  <span class="fl">1.0000</span>  <span class="fl">1.0000</span>

<span class="co"># Numerisk kodning: 1 = low, 2 = high</span>
  edu_<span class="dv">12</span> &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA</span>, <span class="kw">length</span>(education))
  edu_<span class="dv">12</span>[education <span class="op">==</span><span class="st"> &quot;high&quot;</span>] &lt;-<span class="st"> </span><span class="dv">2</span>
  edu_<span class="dv">12</span>[education <span class="op">==</span><span class="st"> &quot;low&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span>
  <span class="kw">summary</span>(edu_<span class="dv">12</span>)
<span class="op">&gt;</span><span class="st">    </span>Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
<span class="op">&gt;</span><span class="st">   </span><span class="fl">1.000</span>   <span class="fl">1.000</span>   <span class="fl">1.000</span>   <span class="fl">1.414</span>   <span class="fl">2.000</span>   <span class="fl">2.000</span></code></pre></div>
<p>Med <strong>Alternativ 2</strong> används funktionen <strong>factor()</strong> för skapa en faktorvariabel <strong>edu_cat</strong></p>
<p>Kommandot <strong>str()</strong> identifierar nu att <strong>edu_cat</strong> har två nivåer med kategorinamnen<br />
<em>“low”</em> and <em>“high”</em>. R tilldelar automatiskt kategorierna <em>nivåer</em>, där “high” är level 1 och “low” är level 2. Observera att nivåer används för att bestämma en rangordning och kan inte användas i aritmetiska beräkningar. Även om valet av nominal- eller ordinalskala i teorin saknar betydelse för en binär variabel är det viktigt att veta ordningen på nivåerna om man hanterar variabeln som en faktor.Det finns nämligen analyser i R där ordningen spelar roll. Nivåerna bestäms utifrån den ordning kategorierna dyker upp i variabeln <em>såvida inte en numerisk variabel görs om till en faktor</em>.</p>
<p>Faktorvariabeln kan beskrivas med <strong>summary()</strong> som redovisar antalet inom respektive utbildningskategori. Däremot kan vi inte använda <strong>mean()</strong> och därmed inte fram andelen med denna funktion.</p>
<p>Det går att i funktionen <strong>factor()</strong> använda argumentet <strong>levels</strong> för att manuellt ange nivåerna. Dessutom kan det i detta exempel uppfattas som förvirrande för användaren att “high” har tilldelats nivå 1 medan “low” är nivå 2. Av dessa skäl ändras därför ordningen med hjälp av argumentet <em>levels</em>.</p>
<p>Vid arbete med faktorer används ofta en funktion (ej att förväxla med <em>argumententet</em> <strong>levels()</strong> för att ändra kategorinamn.I exemplet nedan används denna funktion för att ändra kategorinamn på <span class="math inline">\(edu_cat\)</span>. Koden för att ändra namn är inte uppenbar för nybörjaren och det är enklast om du kopierar koden nedan och ändrar den efter dina behov.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Skapa en faktorvariabel  </span>
  edu_cat &lt;-<span class="st"> </span><span class="kw">factor</span>(education)
  <span class="kw">str</span>(edu_cat)
<span class="op">&gt;</span><span class="st">  </span>Factor w<span class="op">/</span><span class="st"> </span><span class="dv">2</span> levels <span class="st">&quot;high&quot;</span>,<span class="st">&quot;low&quot;</span><span class="op">:</span><span class="st"> </span><span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">2</span> <span class="dv">1</span> ...
  <span class="kw">mean</span>(edu_cat)
<span class="op">&gt;</span><span class="st"> </span>Warning <span class="cf">in</span> <span class="kw">mean.default</span>(edu_cat)<span class="op">:</span><span class="st"> </span>argument is not numeric or logical<span class="op">:</span>
<span class="er">&gt;</span><span class="st"> </span>returning <span class="ot">NA</span>
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="ot">NA</span>
  <span class="kw">summary</span>(edu_cat)
<span class="op">&gt;</span><span class="st"> </span>high  low 
<span class="op">&gt;</span><span class="st">  </span><span class="dv">116</span>  <span class="dv">164</span>
<span class="co"># Test att utföra en räkneoperation på en faktorvariabel</span>
  <span class="kw">mean</span>(edu_cat)
<span class="op">&gt;</span><span class="st"> </span>Warning <span class="cf">in</span> <span class="kw">mean.default</span>(edu_cat)<span class="op">:</span><span class="st"> </span>argument is not numeric or logical<span class="op">:</span>
<span class="er">&gt;</span><span class="st"> </span>returning <span class="ot">NA</span>
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="ot">NA</span>
<span class="co"># Ändra ordningen på nivåerna </span>
  edu_cat &lt;-<span class="st"> </span><span class="kw">factor</span>(education, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>))
  <span class="kw">str</span>(edu_cat)
<span class="op">&gt;</span><span class="st">  </span>Factor w<span class="op">/</span><span class="st"> </span><span class="dv">2</span> levels <span class="st">&quot;low&quot;</span>,<span class="st">&quot;high&quot;</span><span class="op">:</span><span class="st"> </span><span class="dv">2</span> <span class="dv">2</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">2</span> <span class="dv">1</span> <span class="dv">2</span> <span class="dv">1</span> <span class="dv">1</span> <span class="dv">2</span> ...
  <span class="kw">summary</span>(edu_cat)
<span class="op">&gt;</span><span class="st">  </span>low high 
<span class="op">&gt;</span><span class="st">  </span><span class="dv">164</span>  <span class="dv">116</span>
<span class="co"># Ändra för valt element namn i vektor levels(education_cat)  </span>
  <span class="kw">levels</span>(edu_cat)[<span class="kw">levels</span>(edu_cat) <span class="op">==</span><span class="st"> &quot;low&quot;</span>] &lt;-<span class="st"> &quot;Låg utbildning&quot;</span>
  <span class="kw">levels</span>(edu_cat)[<span class="kw">levels</span>(edu_cat) <span class="op">==</span><span class="st"> &quot;high&quot;</span>] &lt;-<span class="st"> &quot;Hög utbildning&quot;</span>
  edu_cat
<span class="op">&gt;</span><span class="st">   </span>[<span class="dv">1</span>] Hög utbildning Hög utbildning Låg utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">   </span>[<span class="dv">5</span>] Hög utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">   </span>[<span class="dv">9</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">13</span>] Hög utbildning Hög utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">17</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">21</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">25</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">29</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">33</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">37</span>] Låg utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">41</span>] Hög utbildning Hög utbildning Låg utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">45</span>] Hög utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">49</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">53</span>] Hög utbildning Hög utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">57</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">61</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">65</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">69</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">73</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">77</span>] Låg utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">81</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">85</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">89</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">93</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st">  </span>[<span class="dv">97</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">101</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">105</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">109</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">113</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">117</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">121</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">125</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">129</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">133</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">137</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">141</span>] Hög utbildning Hög utbildning Låg utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">145</span>] Hög utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">149</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">153</span>] Hög utbildning Hög utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">157</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">161</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">165</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">169</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">173</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">177</span>] Låg utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">181</span>] Hög utbildning Hög utbildning Låg utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">185</span>] Hög utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">189</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">193</span>] Hög utbildning Hög utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">197</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">201</span>] Hög utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">205</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">209</span>] Hög utbildning Låg utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">213</span>] Låg utbildning Hög utbildning Hög utbildning Hög utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">217</span>] Låg utbildning Låg utbildning Hög utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">221</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">225</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">229</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">233</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">237</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">241</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">245</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">249</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">253</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">257</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">261</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">265</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">269</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">273</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">277</span>] Låg utbildning Låg utbildning Låg utbildning Låg utbildning
<span class="op">&gt;</span><span class="st"> </span>Levels<span class="op">:</span><span class="st"> </span>Låg utbildning Hög utbildning</code></pre></div>
<p>Avslutningsvis ska vi på betydelsen av <strong>bortfall</strong>. I exemplet nedan skapas bortfall genom att på några ställen lägga bortfall kodat <em>NA</em> för observation 3 och 10. Vi ser att med <strong>summary()</strong> hanteras bortfallet i bägge fallen, men med <strong>mean()</strong> måste argumentet <strong>na.rm</strong> användas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Skapa en variabel med missing data (NA) i element 3, 10 i den numeriska</span>
<span class="co"># variabeln edu_bin och genomför samma analys som förut</span>
 edu_bin_mis &lt;-<span class="st"> </span>edu_bin
 edu_bin_mis[<span class="dv">3</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
 edu_bin_mis[<span class="dv">10</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
 <span class="kw">mean</span>(edu_bin_mis)
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="ot">NA</span>
<span class="co"># Medelvärde baserat på 278 observationer</span>
 <span class="kw">mean</span>(edu_bin_mis, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="fl">0.4136691</span>
 <span class="kw">summary</span>(edu_bin_mis)
<span class="op">&gt;</span><span class="st">    </span>Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA<span class="st">&#39;s </span>
<span class="st">&gt;  0.0000  0.0000  0.0000  0.4137  1.0000  1.0000       2</span>

<span class="st"># Skapa en variabel med missing data (NA) i element 3, 10 i faktor-variabeln</span>
<span class="st"># edu_cat och genomför samma analys som förut </span>
<span class="st"> edu_cat_mis &lt;- edu_cat</span>
<span class="st"> edu_cat_mis[3] &lt;- NA</span>
<span class="st"> edu_cat_mis[10] &lt;- NA</span>
<span class="st"> summary(edu_cat_mis)</span>
<span class="st">&gt; Låg utbildning Hög utbildning           NA&#39;</span>s 
<span class="op">&gt;</span><span class="st">            </span><span class="dv">163</span>            <span class="dv">115</span>              <span class="dv">2</span></code></pre></div>
</div>
<div id="tabeller-och-en-binär-variabel" class="section level2">
<h2><span class="header-section-number">5.2</span> Tabeller och en binär variabel</h2>
<p>Tabeller och kategorivariabler är direkt relaterade och det går att redovisa en binär variabel med hjälp av tabell-funktionen <strong>table()</strong>. Denna funktion hanterar både en och flera variabler med olika antal kategorier. Vi börjar med att använda <strong>table()</strong> på de tidigare skapade binära variablerna.</p>
<p>Vi ser att <strong>table()</strong> ger frekvenser oavsett om variabeln är numerisk eller en faktor. Det gäller dock att vara uppmärksam på bortfall när <strong>table()</strong> används och för att presentera frekvenser även för bortfall används argumentet <strong>useNA</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">table</span>(edu_bin)
<span class="op">&gt;</span><span class="st"> </span>edu_bin
<span class="op">&gt;</span><span class="st">   </span><span class="dv">0</span>   <span class="dv">1</span> 
<span class="op">&gt;</span><span class="st"> </span><span class="dv">164</span> <span class="dv">116</span>
 <span class="kw">table</span>(edu_cat)
<span class="op">&gt;</span><span class="st"> </span>edu_cat
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning Hög utbildning 
<span class="op">&gt;</span><span class="st">            </span><span class="dv">164</span>            <span class="dv">116</span>
 <span class="kw">table</span>(edu_bin_mis)
<span class="op">&gt;</span><span class="st"> </span>edu_bin_mis
<span class="op">&gt;</span><span class="st">   </span><span class="dv">0</span>   <span class="dv">1</span> 
<span class="op">&gt;</span><span class="st"> </span><span class="dv">163</span> <span class="dv">115</span>
 <span class="kw">table</span>(edu_bin_mis, <span class="dt">useNA =</span> <span class="st">&quot;ifany&quot;</span>)
<span class="op">&gt;</span><span class="st"> </span>edu_bin_mis
<span class="op">&gt;</span><span class="st">    </span><span class="dv">0</span>    <span class="dv">1</span> <span class="op">&lt;</span><span class="ot">NA</span><span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">  </span><span class="dv">163</span>  <span class="dv">115</span>    <span class="dv">2</span>
 <span class="kw">table</span>(edu_cat_mis)
<span class="op">&gt;</span><span class="st"> </span>edu_cat_mis
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning Hög utbildning 
<span class="op">&gt;</span><span class="st">            </span><span class="dv">163</span>            <span class="dv">115</span>
 <span class="kw">table</span>(edu_cat_mis, <span class="dt">useNA =</span> <span class="st">&quot;ifany&quot;</span>)
<span class="op">&gt;</span><span class="st"> </span>edu_cat_mis
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning Hög utbildning           <span class="op">&lt;</span><span class="ot">NA</span><span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">            </span><span class="dv">163</span>            <span class="dv">115</span>              <span class="dv">2</span></code></pre></div>
<p>Varför använda <strong>table()</strong>? Genom att skapa ett tabell-objekt erhålls en flexibilitet genom att funktioner anpassade för tabeller kan användas. Den vanligaste funktionen är <strong>prop.table()</strong> som beräknar andelar (relativa frekvenser, proportioner) baserat på tabellobjektets frekvenser. Att enbart redovisa frekvenser är nämligen inte tillräckligt ur ett analysperspektiv.</p>
<p>Vi skapar nedan ett tabell-objekt med frekvenser, sedan appliceras <strong>prop.table()</strong> för att erhålla andelarna (0.414 och 0.586) för respektive utbildningsnivå.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">&gt;</span><span class="st"> </span><span class="co"># Skapa tabell-objekt med frekvenser från tabell-objektetet</span>
<span class="er">&gt;</span><span class="st">  </span>freq_table_edu_cat &lt;-<span class="st"> </span><span class="kw">table</span>(edu_cat)
<span class="op">&gt;</span><span class="st">  </span>freq_table_edu_cat
<span class="op">&gt;</span><span class="st"> </span>edu_cat
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning Hög utbildning 
<span class="op">&gt;</span><span class="st">            </span><span class="dv">164</span>            <span class="dv">116</span>
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st"> </span><span class="co"># Skapa tabell med andelar från tabell-objektetet</span>
<span class="er">&gt;</span><span class="st">  </span>prop_table_edu_cat &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table_edu_cat)
<span class="op">&gt;</span><span class="st">  </span>prop_table_edu_cat
<span class="op">&gt;</span><span class="st"> </span>edu_cat
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning Hög utbildning 
<span class="op">&gt;</span><span class="st">      </span><span class="fl">0.5857143</span>      <span class="fl">0.4142857</span></code></pre></div>
<p>Som nämnt är det i regel viktigt att beskriva <em>både frekvenser och andelar</em>.</p>
<p>Nedan görs detta genom använda <strong>cbind()</strong> och kombinera tabell-objektet med frekvenser och objektet med andelar med andelar. Sedan namnges kolumnerna <strong>colnames()</strong>. Eftersom <strong>edu_cat</strong>, då det är en faktorvariabel redan har kategorierna namngivna behöver raderna inte namnges. Om så inte vore fallet kunde vi använt <strong>rownames()</strong> för att namnge rader.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">&gt;</span><span class="st">  </span><span class="co"># Kombinera frekvenser och andelar. Passa samtidigt på att avrunda till en decimal och göra om variabeln till procent. </span>
<span class="er">&gt;</span><span class="st">  </span>table_edu &lt;-<span class="st"> </span><span class="kw">cbind</span>(freq_table_edu_cat, <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>prop_table_edu_cat, <span class="dv">1</span>))
<span class="op">&gt;</span><span class="st">  </span>table_edu
<span class="op">&gt;</span><span class="st">                </span>freq_table_edu_cat     
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning                <span class="dv">164</span> <span class="fl">58.6</span>
<span class="op">&gt;</span><span class="st"> </span>Hög utbildning                <span class="dv">116</span> <span class="fl">41.4</span>
<span class="op">&gt;</span><span class="st"> </span><span class="co"># Ge tabellens kolumner namn </span>
<span class="er">&gt;</span><span class="st">  </span><span class="kw">colnames</span>(table_edu) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Frekvens&quot;</span>, <span class="st">&quot;Procent (%)&quot;</span>)
<span class="op">&gt;</span><span class="st">  </span>table_edu
<span class="op">&gt;</span><span class="st">                </span>Frekvens <span class="kw">Procent</span> (%)
<span class="op">&gt;</span><span class="st"> </span>Låg utbildning      <span class="dv">164</span>        <span class="fl">58.6</span>
<span class="op">&gt;</span><span class="st"> </span>Hög utbildning      <span class="dv">116</span>        <span class="fl">41.4</span></code></pre></div>
</div>
<div id="figurer-och-en-binär-variabel" class="section level2">
<h2><span class="header-section-number">5.3</span> Figurer och en binär variabel</h2>
<p>Ett alternativ till tabeller är figurer och för att illustrera kategorivariabler används ofta <strong>stapeldiagram</strong>. R konstrueras sådana med funktionen <strong>barplot()</strong>. <strong>Undvik cirkeldiagram</strong> såvida ett sådant diagram inte är välmotiverat.</p>
<p>Det går att betrakta stapeldiagram som en grafisk representation av en tabell och därför är utgångspunkten ofta (men inte alltid) ett tabell-objekt när man använder <strong>barplot()</strong>.</p>
<p>Nedan konstrueras två figurer, en baserad på tabell-objektet med frekvenser och en baserad på den med andelar. Observera att nedanstående är avsett att illustrera stapeldiagram och ett <strong>stapeldiagram tillför i fallet med en enda binär variabel ingen information.</strong> Det räcker nästan alltid med att istället bara ange numeriska värden.</p>
<p>Det du också ska uppmärksamma i exemplet är axlarna på ett tydligt sätt namngivna! Glöm inte ange axlarna! Det går naturligtvis även att ändra färger, men vi väntar med detta tills figur-kapitlet.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stapeldiagram baserat på tabellen med frekvenser</span>
<span class="kw">barplot</span>(freq_table_edu_cat, <span class="dt">ylab =</span> <span class="st">&quot;Antal&quot;</span>)</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-176-1.png" width="960" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stapeldiagram baserat på tabellen med andelar</span>
<span class="kw">barplot</span>(prop_table_edu_cat, <span class="dt">ylab =</span> <span class="st">&quot;Procent (%)&quot;</span>)</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-176-2.png" width="960" /></p>
</div>
<div id="inferens-för-binär-variabel" class="section level2">
<h2><span class="header-section-number">5.4</span> Inferens för binär variabel</h2>
<p>Hittills har vi ägnat oss åt att beskriva en variabel i stickprovet, men ofta önskar vi också baserat på vårt stickprov uttala oss egenskaper i en population. Det <strong>första</strong> är att beräkna <strong>konfidensintervall</strong> för med viss säkerhet få en uppfattning om andelen i populationen, <span class="math inline">\(p\)</span>. Det <strong>andra</strong> är att med <strong>hypotesprövning undersöka</strong> i vilken utsträckning vårt data stämmer överens med hypotes om populationen, <span class="math inline">\(H_0: p =p_0\)</span>. Huruvida urvalet är gjort med eller utan återlägning saknar praktisk betydelse då urvalsstorleken antas vara liten relativt populationsstorleken.</p>
<p>Vi börjar med att se hur vi kan konstruera ett <strong>konfidensintervall</strong> för andelen <span class="math inline">\(p\)</span> i en <strong>stor population</strong>. Stickprovsandelen är <span class="math inline">\(\hat{p}\)</span> kan definieras som <span class="math inline">\(\hat{p}=\dfrac{k}{n}\)</span> där <span class="math inline">\(n\)</span> är antal försök (antal 0or och 1or) och <span class="math inline">\(k\)</span> är antalet lyckade försök (antal 1or). Givet OSU och <span class="math inline">\(np(1-p)&gt;5\)</span> är andelsestimatorn approximativt normalfördelad och ett konfidensintervall ges av <span class="math display">\[
\hat{p}\pm z_{\alpha/2}\sqrt{\hat{V}(\hat{p})},
\]</span> där <span class="math inline">\(\hat{V}(\hat{p}) = \dfrac{\hat{p}(1-\hat{p})}{n}\)</span> är skattningen av stickprovsandelens varians och <span class="math inline">\(z_{\alpha/2}\)</span> är ett värde från den standardnormalfördelningen baserat på konfidensgraden <span class="math inline">\(100(1-\alpha)\%\)</span>. Notera att felmarginalen är <span class="math inline">\(z_{\alpha/2}\sqrt{\hat{V}(\hat{p})}\)</span>.</p>
<p>Anta variabeln <strong>education</strong> består av mätningar på individer dragna med OSU från en stor population. Målet är att beräkna ett 95% konfidensintervall för andelen med högutbildning i populationen, <span class="math inline">\(p\)</span>. Genom att implementera ovanstående formler kan detta enkelt beräknas i R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Beräkna antalet lyckade försök k (antal 1or)</span>
  k &lt;-<span class="st"> </span>freq_table_edu_cat[<span class="dv">2</span>]  
<span class="co"># Beräkna antal försök (1or or 0r). Denna kodning gör att eventuella NA inte tas med i beräkningen av n</span>
  n &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_edu_cat)
  <span class="co"># Skattning av andelen med hög utbildning. Det går även att använda mean(edu_bin)</span>
  phat &lt;-<span class="st"> </span>k<span class="op">/</span>n   
<span class="co"># Skatta variansen</span>
  vphat &lt;-<span class="st"> </span>phat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat)<span class="op">/</span>n
<span class="co"># Välja konfidensgrad 100*(1-alpha)%</span>
  alpha &lt;-<span class="st"> </span><span class="fl">0.05</span>
<span class="co"># Detta ger värdet för från z-fördelningen med 2.5% i högre svansen  </span>
  z_alpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>((<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>))  
<span class="co"># Konfidensintervallets nedre gräns (lower limit) </span>
  ll &lt;-<span class="st"> </span>phat <span class="op">-</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vphat)
<span class="co"># Konfidensintervallets övre gräns (upper limit) </span>
  ul &lt;-<span class="st"> </span>phat <span class="op">+</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vphat)
  p_KI &lt;-<span class="st"> </span><span class="kw">c</span>(ll, ul)
  p_KI
Hög utbildning Hög utbildning 
     <span class="fl">0.3565876</span>      <span class="fl">0.4719839</span> 
<span class="co"># Undersöker förutsättningen np(1-p) &gt;5. Vi använder phat istället för p eftersom det är det enda vi # har. Man måste alltid undersöka om resultaten går att lita på!</span>
  n<span class="op">*</span>phat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat)
Hög utbildning 
      <span class="fl">67.94286</span> </code></pre></div>
<p>Vi skattar att 41.4% är högutbildade i populationen. Med 95% säkerhet är andelen högutbildade i populationen mellan 35.7% och 47.2%</p>
<p>Vi ska nu se på hur inferens kan göras i form av <strong>hypotesprövning</strong>. Givet OSU och samma förutsättningar som för skapandet av konfidensintervall gäller vid hypotesprövning av <span class="math inline">\(H_0: p = p_{H_0}\)</span> test-statistikan<br />
<span class="math display">\[z = \dfrac{\hat{p} - p_{H_0}}{\sqrt{\dfrac{p_{H_0}(1-p_{H_0})}{n}}}\]</span> är approximativt <span class="math inline">\(N(0,1)\)</span> om <span class="math inline">\(H_0\)</span> är sann.</p>
<p>För att exemplifiera, anta att vi vill undersöka om 40% i populationen har hög utbildning. Vi sätter upp hypoteserna <span class="math inline">\(H_0: p = 0.4\)</span> vs <span class="math inline">\(H_1: p \neq 0.4\)</span>. Utifrån från formeln ovan beräknas det observerat <span class="math inline">\(z\)</span>-värde. Vi ser sedan se hur extremt det är i en standardnormalfördelning för att få fram <span class="math inline">\(p\)</span>-värdet. Om vi önskar fatta ett beslut jämför vi sedan <span class="math inline">\(p\)</span>-värdet mot en förvald signifikansnivå.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># p givet nollhypotesen</span>
  pH0 &lt;-<span class="st"> </span><span class="fl">0.4</span>
<span class="co"># Teststatistika</span>
  zobs &lt;-<span class="st"> </span>(phat <span class="op">-</span><span class="st"> </span>pH0)<span class="op">/</span><span class="kw">sqrt</span>(pH0<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pH0)<span class="op">/</span>n)
  zobs
Hög utbildning 
       <span class="fl">0.48795</span> 
<span class="co"># Vi erhåller ett observerat z-värde. p-värdet är anger hur extremt detta z-värde. </span>
<span class="co"># pnorm() för sannolikheten VÄNSTER om z-värdet. Se Tabell 6.2.A i Formelsamling. För att beräkna # # p-värdet vid två mothypotes används absolutbesloppet (abs()) och vi tar 1 minus och multiplicear med 2. </span>
  p_value &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="kw">abs</span>(zobs)) )
  p_value
Hög utbildning 
     <span class="fl">0.6255852</span> </code></pre></div>
<p>Vi erhåller att <span class="math inline">\(p=\)</span> 0.626. Tolkningen är att <em>givet att andelen högutbildade i populationen skulle vara 40% är sannolikheten 0.63 att observera andelen som observeras eller mer extrem.</em> Data stämmer alltså ganska väl överens med nollhypotesen! Ett beslut på 5% signifikansnivå skulle innebär att vi inte kan förkasta nollhypotesen. Huruvida vi vill fatta ett beslut eller inte beror på målet för analysen.</p>
<p>Det finns dock en inbyggd funktion i R för att göra ovanstående analyser, nämligen <strong>prop.test()</strong>. I funktionen <strong>prop.test()</strong> anges först antalet lyckade försök (1or) samt det totala antalet försök (1or och 0r). Med argumentet <strong>p</strong> anges nollhypotesen och med argumentet <strong>alternative</strong> specificeras mothypotesen. Argumentet <strong>conf.level</strong> anger konfidensgrad för konfidensintervallet. Slutligen bestämmer argumentet <strong>correct</strong> kontinuitetsskorrektion ska användas. Vi använder inte kontinuitetskorrektion på denna kurs och sätter denna till <em>FALSE</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Använd funktionen prop.test() för att skapa konfidensintervall utan korrigering</span>
  edu_analysis &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="dt">x =</span> k, 
                            <span class="dt">n =</span> n, 
                            <span class="dt">p =</span> <span class="fl">0.4</span>, 
                            <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, 
                            <span class="dt">conf.level =</span> <span class="fl">0.95</span>, 
                            <span class="dt">correct =</span> <span class="ot">FALSE</span>)
  edu_analysis

    <span class="dv">1</span><span class="op">-</span>sample proportions test without continuity correction

data<span class="op">:</span><span class="st">  </span>k out of n, null probability <span class="fl">0.4</span>
X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">0.2381</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value =<span class="st"> </span><span class="fl">0.6256</span>
alternative hypothesis<span class="op">:</span><span class="st"> </span>true p is not equal to <span class="fl">0.4</span>
<span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="st"> </span><span class="fl">0.3581276</span> <span class="fl">0.4727639</span>
sample estimates<span class="op">:</span>
<span class="st">        </span>p 
<span class="fl">0.4142857</span> </code></pre></div>
<p>Vi börjar med att se på resultatet från hypotesprövningen och upptäcker exakt samma <span class="math inline">\(p\)</span>-värde som förut! Vårt tidigare observerade <span class="math inline">\(z\)</span>-värde, 0.488 erhålls genom att ta roten ur 0.2380952.</p>
<p>Vidare är konfidensintervallet mycket likt det tidigare framräknade intervallet. De överensstämmer dock inte exakt, vilket beror på att R använder något en annan formel för konfidensintervallet som har något bättre egenskaper om andelen är nära 0 eller 1 och stickprovet är litet.</p>
<p>Låt säg att vi vill hämta värden från analysen som finns i det sparade objektet <strong>edu_analysis</strong>. Genom att använda <strong>str()</strong> ser vi vad som finns sparat. Koden nedan illustrerar hur vi kan hämta <span class="math inline">\(p\)</span>-värdet om vi enbart är intresserad av detta.</p>
<pre><code>## List of 9
##  $ statistic  : Named num 0.238
##   ..- attr(*, &quot;names&quot;)= chr &quot;X-squared&quot;
##  $ parameter  : Named int 1
##   ..- attr(*, &quot;names&quot;)= chr &quot;df&quot;
##  $ p.value    : num 0.626
##  $ estimate   : Named num 0.414
##   ..- attr(*, &quot;names&quot;)= chr &quot;p&quot;
##  $ null.value : Named num 0.4
##   ..- attr(*, &quot;names&quot;)= chr &quot;p&quot;
##  $ conf.int   : num [1:2] 0.358 0.473
##   ..- attr(*, &quot;conf.level&quot;)= num 0.95
##  $ alternative: chr &quot;two.sided&quot;
##  $ method     : chr &quot;1-sample proportions test without continuity correction&quot;
##  $ data.name  : chr &quot;k out of n, null probability 0.4&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;htest&quot;</code></pre>
<pre><code>## [1] 0.6255852</code></pre>
<hr />
<p><img src="docs/images/warning.png" width="5%" /></p>
<style>
div.green{ background-color:#abd4b3; border-radius: 5px; padding: 20px;}
</style>
<div class="green">
<p><font size="5"> Risk med inferens när <span class="math inline">\(p\)</span> är nära 0 eller 1 </font></p>
<ul>
<li>Om andelen i populationen är nära 0 eller 1 krävs stort stickprov för att inferensen ska bli korrekt! Tumregeln <span class="math inline">\(np(1-p)&gt;5\)</span> fungerar dåligt om andelen i populationen är mycket nära 0 eller 1. Konsekvensen blir för lägre konfidensgrad och ett högre Typ-I fel än i förväg angivet. Vi gör fel oftare!</li>
</ul>
<p>Beträffande konfidensintervall är Wilson score interval, som är det konfidensintervall R använder i <strong>prop.test</strong>, ett något bättre alternativ än den formeln som vi använder. I de absolut flesta fall har det inget betydelse om vi väljer <strong>prop.test()</strong> eller intervallet som baseras på normalapproximation.</p>
<p>För hypotesprövning finns alternativet att använda ett så kallat exakt binomial-test. Detta test introduceras emellertid inte här utan vi hänvisar till funktionen <strong>binom.test()</strong> och tillhörande dokumentation.</p>
<p>Var som sagt uppmärksam om andelen är nära 0 eller nära 1!</p>
<p><strong>Undersök på egen hand med följande app!</strong></p>
<p><a href="https://jetty.im.uu.se/shiny/ConfidenceIntervals_prop/" class="uri">https://jetty.im.uu.se/shiny/ConfidenceIntervals_prop/</a></p>
</div>
<hr />
<p><img src="docs/images/note.png" width="5%" /></p>
<style>
div.yellow{ background-color:#FFFA94; border-radius: 5px; padding: 20px;}
</style>
<div class="yellow">
<p><font size="5"> Test av andelar eller <span class="math inline">\(\chi^2\)</span>-test? </font></p>
<ul>
<li>Ett <strong>prop.test()</strong> med två-sidig mothypotes är likvärdigt med <span class="math inline">\(\chi^2\)</span>-test. <span class="math inline">\(\chi^2\)</span>-statistikan är samma som <span class="math inline">\(z\)</span>-statistikan i kvadrat! Problemet med test av <span class="math inline">\(p\)</span> kan nämligen formuleras som ett goodness-of-fit test med observerade frekvenser (<span class="math inline">\(116\)</span> 1or och <span class="math inline">\(164\)</span> 0or) och under nollhypotesen förväntade frekvenser (<span class="math inline">\(np_{H_0}=112\)</span> 1or och <span class="math inline">\(n(1-p_{H_0})=168\)</span> 0r). Vi illusterar i en tabell:</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">1or</th>
<th align="center">0or</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">116 (112)</td>
<td align="center">164 (168)</td>
</tr>
</tbody>
</table>
<p>Formeln för <span class="math inline">\(\chi^2\)</span>-testet går det sedan att tillämpa <span class="math display">\[\chi^2 = \sum \dfrac{(O_i-E_i)^2}{E_i} = \dfrac{(116-112)^2}{112} + \dfrac{(164-168)^2}{168}=0.2381\]</span> vilket i detta fall jämförs med en <span class="math inline">\(\chi^2\)</span>-fördelning med 1 frihetsgrad. Notera att mothypotesen vid <span class="math inline">\(\chi^2\)</span>-testet alltid är två-sidig, vilket motiverar användningen av <strong>prop.test()</strong>.</p>
</div>
<hr />
</div>
<div id="deskription-av-två-binära-variabler" class="section level2">
<h2><span class="header-section-number">5.5</span> Deskription av två binära variabler</h2>
<p>För två binära kan man välja att analysera dem var för sig eller så är målet att undersöka hur variablerna är relaterade till varandra. Det primära analys verktyget för två binär variabler är <strong>table()</strong>.</p>
</div>
<div id="tabeller-och-två-binära-variabler" class="section level2">
<h2><span class="header-section-number">5.6</span> Tabeller och två binära variabler</h2>
<p>Även om funktionen <strong>table()</strong> kan användas vid analys av en enda variabel, så är den framför allt användbar för att skapa korstabeller, dvs analys av två kategorivariabler samtidigt. I <strong>table()</strong> anges variabeln som ska finnas på raden först, sedan variabeln redovisas. Tabellen som erhålls kallas i fallet med två variabler för tvåvägs-korstabell. Om det går att översätta variablerna i termer av oberoende variabel och beroende variabel, sätts den oberoende variabeln i regel kolumnsvis (x-axel) och den beroende variabeln radvis (y-axel).</p>
<p>Vi ska nu beskriva sambandet mellan utbildningsnivå och rökning. Först skapas en korstabell med frekvenser. Baserat på denna skapas sedan en korstabell med andelar. Notera att det kräver en del pusslande, men i gengäld erhålls stor flexibilitet vad gäller den slutliga utformningen av tabellen.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Skapa en variabel smoker som är 1 om rökare och 0 om icke-rökare  </span>
  smoker &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,
              <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, 
              <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>,
              <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,
              <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>)
<span class="co"># Korstabulering av edu_bin och smoker (rökning radvis och utbildning kolumnvis)</span>
  freq_table_edu_smoke &lt;-<span class="st"> </span><span class="kw">table</span>(smoker, edu_bin)
  freq_table_edu_smoke
<span class="op">&gt;</span><span class="st">       </span>edu_bin
<span class="op">&gt;</span><span class="st"> </span>smoker  <span class="dv">0</span>  <span class="dv">1</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">0</span> <span class="dv">76</span> <span class="dv">80</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">1</span> <span class="dv">88</span> <span class="dv">36</span></code></pre></div>
<p>Vi har en tabell med frekvenser, men för att använda tabellen måste den i regel modifieras. Dels måste rader och kolumner tydligare namnges, dels måste sambandet åskådliggöras bättre om sambandsanalys är syftet. Det är nämligen svårt avläsa samband med enbart frekvenser, därför måste andelar (procent) anges. Precis som tidigare används därför funktionen <strong>prop.table()</strong> på ett objekt från <strong>table()</strong>. En två-vägs kortstabell ger nu <strong>prop.table()</strong> tre möjligheter att beräkna andelar:</p>
<ul>
<li>Andelar baserade på totala antalet (default)</li>
<li>Andelar beräknade utifrån radvisa totaler i nämnarna, genom att sätta argumentet <strong>margin = 1</strong></li>
<li>Andelar baserade på kolumnvisa totaler i nämnarna, genom sätta argumentet <strong>margin = 2</strong>.</li>
</ul>
<p>Notera att det är <strong>mycket viktigt</strong> att välja rätt andelar att beräkna eftersom dessa styr tolkningen av resultaten. Vi illustrerar nu hur andelarna beräknas i R och tolkar dem sen.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Andelar baserat alla</span>
  table_all &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table_edu_smoke)
  table_all
<span class="op">&gt;</span><span class="st">       </span>edu_bin
<span class="op">&gt;</span><span class="st"> </span>smoker         <span class="dv">0</span>         <span class="dv">1</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">0</span> <span class="fl">0.2714286</span> <span class="fl">0.2857143</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">1</span> <span class="fl">0.3142857</span> <span class="fl">0.1285714</span>
<span class="co"># Andelar baserat rader</span>
  table_row_prop &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table_edu_smoke, <span class="dt">margin =</span> <span class="dv">1</span>)
  table_row_prop 
<span class="op">&gt;</span><span class="st">       </span>edu_bin
<span class="op">&gt;</span><span class="st"> </span>smoker         <span class="dv">0</span>         <span class="dv">1</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">0</span> <span class="fl">0.4871795</span> <span class="fl">0.5128205</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">1</span> <span class="fl">0.7096774</span> <span class="fl">0.2903226</span>
<span class="co"># Andelar baserat kolumner</span>
  table_column_prop &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table_edu_smoke, <span class="dt">margin =</span> <span class="dv">2</span>)
  table_column_prop  
<span class="op">&gt;</span><span class="st">       </span>edu_bin
<span class="op">&gt;</span><span class="st"> </span>smoker         <span class="dv">0</span>         <span class="dv">1</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">0</span> <span class="fl">0.4634146</span> <span class="fl">0.6896552</span>
<span class="op">&gt;</span><span class="st">      </span><span class="dv">1</span> <span class="fl">0.5365854</span> <span class="fl">0.3103448</span></code></pre></div>
<p>Spendera tid med att tolka de olika tabellerna!</p>
<p>För att förenkla tolkningen beskriver vi sambanden i termer av sannolikheter.</p>
<ul>
<li>Den första tabellen visar att av alla i undersökningen är 27.1% icke-rökare och har låg utbildning. Om urvalet är slumpmässigt är detta således en skattning av sannolikheten <span class="math inline">\(\Pr(\text{Icke-rökare}\,\, \&amp; \,\, \text{Låg utbildning})\)</span>. På motsvarande sätt är 28.6%, 31.4% och 12.9% skattningar av <span class="math inline">\(\Pr(\text{Icke-rökare}\,\, \&amp; \,\, \text{Hög utbildning})\)</span>, <span class="math inline">\(\Pr(\text{Rökare}\,\, \&amp; \,\, \text{Låg utbildning})\)</span> och <span class="math inline">\(\Pr(\text{Rökare}\,\, \&amp; \,\, \text{Hög utbildning})\)</span>. Huruvida dessa skattningar är relevanta beror på syftet med undersökningen.</li>
<li>Den andra tabellen visar, genom att beräkna radprocent, att bland icke-rökarna har 48.7% låg utbildning. Det innebär naturligtvis att bland icke-rökarna har 51.3% hög utbildning. Om urvalet är slumpmässigt är dessa skattningar av <span class="math inline">\(\Pr(\text{Låg utbildning}|\text{Icke-rökare})\)</span> och <span class="math inline">\(\Pr(\text{Hög utbildning}|\text{Icke-rökare})\)</span>. På motsvarande sätt har 71% låg utbildning respektive 29% hög utbildning bland rökarna. <span class="math inline">\(\Pr(\text{Låg utbildning}|\text{Rökare})\)</span> och <span class="math inline">\(\Pr(\text{Hög utbildning}|\text{Rökare})\)</span>. Vi kan alltså med denna analys jämföra utbildningsnivån bland icke-rökare och rökare.</li>
<li>Den tredje tabellen visar, genom att beräkna kolumnprocent, att bland de lågutbildade röker 53.7% medan bland de högutbildade röker 31%. Detta är således skattningar av <span class="math inline">\(\Pr(\text{Rökare} | \text{Låg utbildning})\)</span> respektive <span class="math inline">\(\Pr(\text{Rökare} | \text{Hög utbildning})\)</span>. På motsvarande sätt är 46.3% och 69% skattningar av <span class="math inline">\(\Pr(\text{Icke-rökare}|\text{Låg utbildning})\)</span> och <span class="math inline">\(\Pr(\text{Icke-rökare}|\text{Hög utbildning})\)</span>. Vi kan konstatera att i stickprovet är andelen rökare större bland lågutbildade än högutbildade.</li>
</ul>
<p>Vilken tabell som redovisas beror således på frågeställningen. Om syftet är att studera om utbildning påverkar benägenheten att röka är det den tredje tabellen den som ska redovisas. Det är då enkelt att jämföra andelarna som röker i respektive utbildningskategori.</p>
<p>Vi konstruerar nu en korstabell innehåller <em>både</em> frekvenser och andelar baserade på kolumner och som tydligt beskriver sambandet. Tabellen konstrueras på motsvarande sätt som tidigare med **cbind()*.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Skapa tabell för presentation av analys</span>
  table_edu_smoke &lt;-<span class="st"> </span><span class="kw">cbind</span>(freq_table_edu_smoke[,<span class="dv">1</span>], <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>table_column_prop[,<span class="dv">1</span>], <span class="dv">1</span>),
                           freq_table_edu_smoke[,<span class="dv">2</span>], <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>table_column_prop[,<span class="dv">2</span>], <span class="dv">1</span>))
  <span class="kw">colnames</span>( table_edu_smoke ) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Låg (n)&quot;</span>, <span class="st">&quot;Låg (%)&quot;</span>, <span class="st">&quot;Hög (n)&quot;</span>, <span class="st">&quot;Hög (%)&quot;</span>)
  <span class="kw">rownames</span>( table_edu_smoke ) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>)
  table_edu_smoke
<span class="op">&gt;</span><span class="st">             </span>Lå<span class="kw">g</span> (n) Lå<span class="kw">g</span> (<span class="op">%) Hög (n) Hög (%</span>)
<span class="op">&gt;</span><span class="st"> </span>Icke<span class="op">-</span>rökare      <span class="dv">76</span>    <span class="fl">46.3</span>      <span class="dv">80</span>      <span class="dv">69</span>
<span class="op">&gt;</span><span class="st"> </span>Rökare           <span class="dv">88</span>    <span class="fl">53.7</span>      <span class="dv">36</span>      <span class="dv">31</span></code></pre></div>
<p>Avslutningsvis, för fullständighetens skull, används funktionen <strong>addmargins()</strong> på tabellobjektet för att addera marginalsummor till tabellen. Genom att ange 1 adderas en ny rad som innehålla kolumnsummansummor, genom att ange två adderas en ny kolumn till tabellen med radsumman. Anges inget argument adderas både en rad och en kolumn med summor.</p>
<p>Nu är vi klara med tabellen! Det som återstår är att exportera den till ett ordbehandlingsprogram eller ett bildspel, men detta beskrivs i ett senare avsnitt.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> table_edu_smoke_final &lt;-<span class="st"> </span><span class="kw">addmargins</span>(table_edu_smoke, <span class="dv">1</span>) 
 <span class="kw">rownames</span>( table_edu_smoke_final ) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>, <span class="st">&quot;Summa&quot;</span>)
 table_edu_smoke_final 
<span class="op">&gt;</span><span class="st">             </span>Lå<span class="kw">g</span> (n) Lå<span class="kw">g</span> (<span class="op">%) Hög (n) Hög (%</span>)
<span class="op">&gt;</span><span class="st"> </span>Icke<span class="op">-</span>rökare      <span class="dv">76</span>    <span class="fl">46.3</span>      <span class="dv">80</span>      <span class="dv">69</span>
<span class="op">&gt;</span><span class="st"> </span>Rökare           <span class="dv">88</span>    <span class="fl">53.7</span>      <span class="dv">36</span>      <span class="dv">31</span>
<span class="op">&gt;</span><span class="st"> </span>Summa           <span class="dv">164</span>   <span class="fl">100.0</span>     <span class="dv">116</span>     <span class="dv">100</span></code></pre></div>
</div>
<div id="kvantifiering-av-samband-mellan-två-binära-variabler" class="section level2">
<h2><span class="header-section-number">5.7</span> Kvantifiering av samband mellan två binära variabler</h2>
<p>Samband eller beroende mellan två binära variabler kan kvantifieras med olika mått. Ett vanligt sätt är användning av <span class="math inline">\(\chi^2\)</span>-måttet för att testa om två variabler är oberoende och kan sägas undersöka hur starkt ett samband är. Förutom <span class="math inline">\(\chi^2\)</span>-måttet finns en rad andra mått för graden av beroende, såsom Lambda-koefficienten, Cramérs V och tetrakorisk korrelation. Dessa mått introduceras inte här, men det kan vara bra att känna till att det finns alternativ till ^2$-måttet.</p>
<p>Ofta vill undersökaren dock relatera sambandet till en konkret frågeställning som inte bara handlar om beroende, det vill säga man önskar få en uppfattning av storleken på sambandet. De tre vanligaste måtten på storleken på samband (så kallade effektstorlekar) mellan två binära variabler är:</p>
<ul>
<li><strong>Skillnaden i andelar</strong> (absolut jämförelse av andelar): <span class="math display">\[p_{diff} = \Pr(Y=1|X=1) - \Pr(Y=0|X=1) = p_1 - p_0\]</span>. Skillnaden i andelar kan anta värdena <span class="math inline">\(-1 \leq p_{diff} \leq1\)</span>. Ofta kallat riskdifferens. Skillnaden i andelar är även en skillnad i procentenheter. <span class="math inline">\(0\)</span> indikerar ingen skillnad. Positiva värden indikerar en högre sannolikhet i grupp 1 jämfört med grupp 0. Negativa värden indikerar en lägre sannolikhet i grupp 1 jämfört med grupp 0.</li>
<li><strong>Kvoten av andelar</strong> (relativ jämförelse av andelar): <span class="math display">\[p_{kvot} = \dfrac{\Pr(Y=1|X=1)}{\Pr(Y=0|X=1)}= p_1/p_0\]</span>. Kvoten av andelar kan anta värdena <span class="math inline">\(0 \leq p_{kvot} &lt; \infty\)</span>. Ofta kallat relativ risk. <span class="math inline">\(p_{kvot}=1\)</span> indikerar ingen skillnad mellan grupperna. <span class="math inline">\(p_{kvot} &gt;1\)</span> indikerar en högre sannolikhet i grupp 1 jämfört med grupp 0. <span class="math inline">\(p_{kvot} &lt; 1\)</span> indikerar en lägre sannolikhet i grupp 1 jämfört med grupp 0.</li>
<li><strong>Oddskvoten</strong> (relativ jämförelse av odds): <span class="math display">\[OR = \dfrac{Odds(X=1)}{Odds(X=0)}=\dfrac{\dfrac{\Pr(Y=1|X=1)}{1 - \Pr(Y=1|X=1)}}{\dfrac{\Pr(Y=1|X=0)}{1 - \Pr(Y=1|X=0)}} = \dfrac{p_1/(1-p_1)}{p_0/(1-p_0)},\]</span>, där oddset för en händelse givet <span class="math inline">\(x\)</span> är definierat som <span class="math display">\[Odds(X=x)=\dfrac{\Pr(Y=1|X=x)}{1-(\Pr(Y=1|X=x)}=\dfrac{\Pr(Y=1|X=x)}{\Pr(Y=0|X=x)}.\]</span> Oddskvoten kan anta värdena <span class="math inline">\(0 \leq OR &lt; \infty\)</span>. Ofta kallat oddsratio. <span class="math inline">\(OR=1\)</span> indikerar ingen skillnad mellan grupperna. <span class="math inline">\(OR &gt;1\)</span> indikerar en högre sannolikhet i grupp 1 jämfört med grupp 0. <span class="math inline">\(OR &lt; 1\)</span> indikerar en lägre sannolikhet i grupp 1 jämfört med grupp 0.</li>
</ul>
<p>Notera att ovanstående mått är definierade utifrån populationen. I praktiken använder vi därför motsvarigheterna i stickprovet <span class="math inline">\(\hat{p_1}=k_1/n_1\)</span> och <span class="math inline">\(\hat{p_0}=k_0/n_0\)</span>, där <span class="math inline">\(k_1\)</span> och <span class="math inline">\(k_0\)</span> är antalet lyckade försök (1or) i respektive <span class="math inline">\(x\)</span>-kategori och <span class="math inline">\(n_1\)</span> och <span class="math inline">\(n_0\)</span> är antalet försök i respektive <span class="math inline">\(x\)</span>-kategori.</p>
<p>Vilket av dessa tre mått som är mest relevant att presentera beror på syftet med undersökningen och ofta bör åtminstone både ett absolut mått och ett relativt mått presenteras. Måste man göra en indelning kan absoluta jämförelser av andelar ofta (men inte alltid!) vara mest policy-relevant eftersom måttet kan tolkas som en skillnad i procenheter mellan två stycken grupper. Däremot kan en relativ jämförelse av andelar uppfattas som mer relevant för en enskild individ. Detta beror dock på andra faktorer som populationsstorleken!</p>
<p>Eftersom oddskvoten inte är lika enkel att förstå som relativa andelar är det ett mått som i regel främst väljs på grund av studiedesign eller val av statistiska analysmetod.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Beräkna andelen rökare bland högutbildade. Det går även att använda mean( smoker[edu_bin == 1] ) eller table_row_prop[2,2]  </span>
k1 &lt;-<span class="st">  </span>freq_table_edu_smoke[<span class="dv">2</span>,<span class="dv">2</span>] 
n1 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_edu_smoke[,<span class="dv">2</span>])   <span class="co"># Summera antal i kolumn 2, dvs de i kategori 1</span>
phat1 &lt;-<span class="st"> </span>k1<span class="op">/</span>n1
<span class="co"># Beräkna andelen rökare bland lågutbildade. Det går även att använda mean( smoker[edu_bin == 0] ) eller table_row_prop[2,1] </span>
k0 &lt;-<span class="st"> </span>freq_table_edu_smoke[<span class="dv">2</span>,<span class="dv">1</span>]
n0 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_edu_smoke[,<span class="dv">1</span>])   <span class="co"># Summera antal i kolumn 1, dvs de i kategori 0</span>
phat0 &lt;-<span class="st"> </span>k0<span class="op">/</span>n0

<span class="co"># Skillnad i andelar </span>
phat_diff &lt;-<span class="st"> </span>phat1 <span class="op">-</span><span class="st"> </span>phat0
phat_diff
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.2262405</span>
<span class="co"># kvot av andelar </span>
phat_kvot &lt;-<span class="st"> </span>phat1<span class="op">/</span>phat0
phat_kvot
[<span class="dv">1</span>] <span class="fl">0.5783699</span>
<span class="co"># oddskvot</span>
orhat &lt;-<span class="st"> </span>(phat1<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>phat1))<span class="op">/</span>((phat0<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>phat0)))
orhat
[<span class="dv">1</span>] <span class="fl">0.3886364</span></code></pre></div>
<p>Tolkningen av dessa tre resultat är:</p>
<ul>
<li>Bland högutbildade röker 22 procentenheter mindre jämfört med lågutbildade.</li>
<li>Högutbildade har 100(1 - 0.578)% = 42.2% reducerad sannolikhet (risk) att röka jämfört med lågutbildade.</li>
<li>Högutbildade har 100(1 - 0.389)% = 62.1% reducerat odds för att röka jämfört lågutbildade.</li>
</ul>
<p>En pedagogisk poäng skulle vara att vända på analysen, dvs att sätta den kategori som ökar sannolikheten (lågutbildade) som 1 och jämförelsekategorin (högutbildade) som 0. Detta skulle ge följande resultat och tolkning:</p>
<ul>
<li>Bland lågutbildade röker 22 procentenheter fler jämfört med lågutbildade.</li>
<li>Lågutbildade har 72.9% ökad sannolikhet att röka jämfört med högutbildade.</li>
<li>Lågutbildade har 2.57 gånger större odds för att röka jämfört med lågutbildade.</li>
</ul>
<hr />
<p><img src="docs/images/note.png" width="5%" /></p>
<style>
div.yellow{ background-color:#FFFA94; border-radius: 5px; padding: 20px;}
</style>
<div class="yellow">
<p><font size="5"> Absoluta eller relativa jämförelser av andelar? </font></p>
<ul>
<li><p>Anta att 0.2% (2 av 1000) av alla som får Covid-19 dör. Ett studie visar att ett nytt antiviralt läkemedel leder till att endast 0.1% (1 av 1000) dör. Det är en skillnad i dödlighet på endast 0.1 procentenheter, men för individen innebär detta en halverad risk för att dö! Huruvida det är policyrelevant beror dock på hur många man räknar med att drabbas. Låt säg att bara 10 000 drabbas av Covid-19, då skulle läkemedlet rädda 10 liv. Skulle däremot 1 miljon få Covid-19 då skulle läkemedlet potentiellt rädda 10 000 liv.</p></li>
<li><p>Anta att arbetsförmedlingen introducerar ett nytt åtgärdsprogram riktat mot gymnasieungdomar som riskerar att inte slutföra gymnasieskolan. Bland eleverna som deltar i programmet kommer 90% få slutbetyg, medan i kontrollgrupp får 70% slutbetyg Det är alltså en skillnad på hela 20 procentenheter. För en individ ökar dock sannolikheten till behörighet med endast 29%.</p></li>
</ul>
</div>
<hr />
</div>
<div id="figurer-och-två-binära-variabler" class="section level2">
<h2><span class="header-section-number">5.8</span> Figurer och två binära variabler</h2>
<p>Relationen mellan tabeller och figurer blir tydlig när man skapar diagram. Återigen tillämpas <strong>barplot()</strong> på tabellobjekten.</p>
<ul>
<li>Med <em>freq_table_edu_smoke</em> skapas ett stapeldiagram som redovisar antalet i respektive kategori. Vad denna figur visar är att det finns fler lågutbildade än högutbildade. Dessutom relaterar diagrammet direkt till frekvenserna i varje cell i tabellen. Denna figur är kan vara användbar i en del fall, men ofta blir det svårt att utläsa samband.</li>
<li>Med <em>table_row_prop</em> blir figuren meninglös eftersom andelen lågutbildade är mer än 1!</li>
<li>Med <em>table_col_prop</em> ges en tydlig bild av om andelen rökare inom respektive utbildning. Om vi däremot önskar få någon uppfattning om hur <em>många</em> som finns i respektive utbildningskategori ger denna figur ingen information.</li>
</ul>
<p>Vi illusterar nedan. För fullständighetens finns även argumentet <strong>legend</strong> med i koden. En <strong>legend</strong> i R är en förklaring av komponenterna i figuren Prova kör de olika figurerna nedan och relatera till koden.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(freq_table_edu_smoke)</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-189-1.png" width="384" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">
<span class="kw">barplot</span>( freq_table_edu_smoke,                                <span class="co"># Tabellen</span>
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>),   <span class="co"># Ge namn till staplarna</span>
         <span class="dt">ylab =</span> <span class="st">&quot;Andel&quot;</span>,                                      <span class="co"># Namn till y-axeln</span>
         <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>),                 <span class="co"># Namn till färgerna</span>
         <span class="dt">args.legend =</span>  <span class="kw">c</span>(<span class="dt">y =</span> <span class="dv">190</span>, <span class="dt">horiz =</span> <span class="ot">TRUE</span>, <span class="dt">bty =</span><span class="st">&#39;n&#39;</span>))   <span class="co"># Ställa in position, horisontell, samt ta bort</span></code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-189-2.png" width="384" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">                                                              <span class="co"># kantlinje i legend.</span>
<span class="kw">barplot</span>( table_row_prop, 
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>), 
         <span class="dt">ylab =</span> <span class="st">&quot;Andel&quot;</span>, 
         <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>), 
         <span class="dt">args.legend =</span>  <span class="kw">c</span>(<span class="dt">y =</span> <span class="fl">1.4</span>, <span class="dt">horiz =</span> <span class="ot">TRUE</span>, <span class="dt">bty =</span><span class="st">&#39;n&#39;</span>))</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-189-3.png" width="384" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">
<span class="kw">barplot</span>( table_column_prop, 
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>), 
         <span class="dt">ylab =</span> <span class="st">&quot;Andel&quot;</span>, 
         <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>), 
         <span class="dt">args.legend =</span>  <span class="kw">c</span>(<span class="dt">y =</span> <span class="fl">1.2</span>, <span class="dt">horiz =</span> <span class="ot">TRUE</span>, <span class="dt">bty =</span><span class="st">&#39;n&#39;</span>))</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-189-4.png" width="384" /></p>
<p>Anta att syftet är att studera andelen rökare inom respektive utbildningskategori och vi väljer därför figuren som baseras på <strong>table_column_prop</strong>.</p>
<p>Med argumentet <strong>beside</strong> och placering av staplarna bredvid varandra kan sambandet eventuellt tydligare åskådliggöras. Alternativt skapas ett stapeldiagram baserad på enbart rad 2 från tabellen, dvs andelen rökare i respektive kategori.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>( table_column_prop, <span class="dt">beside=</span><span class="ot">TRUE</span>, 
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>), 
         <span class="dt">ylab =</span> <span class="st">&quot;Andel&quot;</span>, 
         <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Icke-rökare&quot;</span>, <span class="st">&quot;Rökare&quot;</span>),
         <span class="dt">args.legend =</span>  <span class="kw">c</span>(<span class="dt">y =</span> <span class="fl">0.8</span>, <span class="dt">horiz =</span> <span class="ot">TRUE</span>, <span class="dt">bty =</span><span class="st">&#39;n&#39;</span>))</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-190-1.png" width="384" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">
<span class="kw">barplot</span>( table_row_prop[<span class="dv">2</span>,], 
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>), 
         <span class="dt">ylab =</span> <span class="st">&quot;Andel rökare&quot;</span>)</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-190-2.png" width="384" /></p>
<hr />
<p><img src="docs/images/tip.png" width="5%" /></p>
<style>
div.burly{ background-color:#EAF2F8; border-radius: 5px; padding: 20px;}
</style>
<div class="burly">
<p><font size="5"> Tips för ytterligare modifering av stapeldiagram </font></p>
<p>Varför inte unyttja den funktionalitet som R erbjuder?</p>
<p>Den sista figuren är korrekt, men det kan behövas ytterligare modifierng för att få figuren tillräckligt bra vilket enkelt görs i R. Nedan är en illustration för den intresserade. Enklast är att ta färdig kod och modifiera efter eget behov. Om du inte förstår färdig kod, testa att ändra i koden och se vad som händer!</p>
<p>Figuren nedan skapas genom att:</p>
<ol style="list-style-type: decimal">
<li>Vi lägger till procent ovanför staplarna med hjälp av funktionen <strong>text()</strong>. I denna funktion anges koordinater (x,y) för var texten ska in, där x-koordinaten är staplarnas placering i objektet my_bar och ofta får man testa sig fram. Med argumentet <strong>labels</strong> bestäms vad som ska stå över staplarna. Funktionen <strong>paste</strong> används för att sammanfoga numeriska värden och text, i detta fall procenttecknet.</li>
<li>Vi ändrar färg på figuren samt gränserna för y-axeln med argumentet <strong>ylim</strong>. Annars får inte procentsiffrorna plats.</li>
<li>Vi använder argument som börjar med <strong>cex</strong> för att bestämma storlekarna på axlar osv.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Gör om andelar till procent </span>
  percentages_smoker &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>table_row_prop[<span class="dv">2</span>,], <span class="dv">1</span>)
<span class="co"># Skapa objekt så vi kan hämta information från figurobjekt </span>
  my_bar &lt;-<span class="st"> </span><span class="kw">barplot</span>(  percentages_smoker, 
                      <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Låg utbildning&quot;</span>, <span class="st">&quot;Hög utbildning&quot;</span>), 
                      <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">80</span>), 
                      <span class="dt">col =</span> <span class="st">&quot;lightblue&quot;</span>,
                      <span class="dt">border =</span> <span class="st">&quot;lightblue&quot;</span>,
                      <span class="dt">ylab =</span> <span class="st">&quot;Röker (%)&quot;</span>,
                      <span class="dt">cex.axis =</span> <span class="fl">1.1</span>,
                      <span class="dt">cex.lab =</span> <span class="fl">1.1</span>,
                      <span class="dt">cex.names=</span><span class="fl">1.1</span>)
<span class="co"># Lägg till text i figuren  </span>
  <span class="kw">text</span>(<span class="dt">x =</span> my_bar,                                    <span class="co"># x-koordinat för placering av text</span>
       <span class="dt">y =</span> percentages_smoker <span class="op">+</span><span class="st"> </span><span class="dv">6</span>,                    <span class="co"># y-koordinat för placering av test</span>
       <span class="dt">labels =</span> <span class="kw">paste</span>(percentages_smoker, <span class="st">&quot;%&quot;</span>,  <span class="dt">sep=</span><span class="st">&quot;&quot;</span>),   <span class="co"># Text</span>
       <span class="dt">cex =</span> <span class="fl">1.1</span>)                                     <span class="co"># Storlek på text</span></code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-192-1.png" width="384" /></p>
</div>
<hr />
</div>
<div id="inferens-för-två-binära-variabler" class="section level2">
<h2><span class="header-section-number">5.9</span> Inferens för två binära variabler</h2>
<p>Anta nu att målet är generalisera analyserna av stickprovet till en population.</p>
<p>Vi vill nu göra inferens för skillnaden i populationsandelar <span class="math inline">\(p_1\)</span> och <span class="math inline">\(p_0\)</span> i två population. Vi drar två oberoende OSU. Givet att förutsättningarna för normalapproximation håller ges ett konfidensintervall av:</p>
<ul>
<li><span class="math display">\[\hat{p_1} - \hat{p_0}\pm  z_{\alpha/2}\sqrt{\dfrac{\hat{p_1}(1-\hat{p_1})}{n_1} + \dfrac{\hat{p_0}(1-\hat{p_0})}{n_0}}\]</span></li>
</ul>
<p>Konfidensintervallet kan beräknas antingen med <strong>prop.test()</strong> eller genom att implementera formeln ovan.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Version 1</span>
x0 &lt;-<span class="st">  </span>freq_table_edu_smoke[<span class="dv">2</span>,<span class="dv">1</span>]
x1 &lt;-<span class="st">  </span>freq_table_edu_smoke[<span class="dv">2</span>,<span class="dv">2</span>]
n0 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_edu_smoke[,<span class="dv">1</span>])
n1 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_edu_smoke[,<span class="dv">2</span>])
resultat &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="kw">c</span>(x1, x0), <span class="kw">c</span>(n1, n0), <span class="dt">correct =</span> <span class="ot">FALSE</span>)
p_differens &lt;-<span class="st"> </span>resultat<span class="op">$</span>estimate[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>resultat<span class="op">$</span>estimate[<span class="dv">2</span>]
p_diff_KI_resultat &lt;-<span class="st"> </span>resultat<span class="op">$</span>conf.int
p_differens
    prop <span class="dv">1</span> 
<span class="op">-</span><span class="fl">0.2262405</span> 
p_diff_KI_resultat 
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.3398732</span> <span class="op">-</span><span class="fl">0.1126079</span>
<span class="kw">attr</span>(,<span class="st">&quot;conf.level&quot;</span>)
[<span class="dv">1</span>] <span class="fl">0.95</span>

<span class="co"># Version 2</span>
phat1 &lt;-<span class="st"> </span><span class="kw">mean</span>(smoker[edu_bin <span class="op">==</span><span class="st"> </span><span class="dv">1</span>])
phat0 &lt;-<span class="st"> </span><span class="kw">mean</span>(smoker[edu_bin <span class="op">==</span><span class="st"> </span><span class="dv">0</span>])
n1 &lt;-<span class="st"> </span><span class="kw">sum</span>(edu_bin <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)
n0 &lt;-<span class="st"> </span><span class="kw">sum</span>(edu_bin <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)
phatdiff &lt;-<span class="st"> </span>phat1 <span class="op">-</span><span class="st"> </span>phat0
vhat_pdiff &lt;-<span class="st"> </span>phat1<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat1)<span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span>phat0<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat0)<span class="op">/</span>n0 
alpha &lt;-<span class="st"> </span><span class="fl">0.05</span>
z_alpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha<span class="op">/</span><span class="dv">2</span>)
ll &lt;-<span class="st"> </span>phat_diff <span class="op">-</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vhat_pdiff)
ul &lt;-<span class="st"> </span>phat_diff <span class="op">+</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vhat_pdiff)
p_diff_KI &lt;-<span class="st"> </span><span class="kw">c</span>(ll, ul)
phatdiff
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.2262405</span>
p_diff_KI
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.3398732</span> <span class="op">-</span><span class="fl">0.1126079</span>

<span class="co"># Kolla förutsättningarna!</span>
phat1<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat1)<span class="op">*</span>n1
[<span class="dv">1</span>] <span class="fl">24.82759</span>
phat0<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>phat0)<span class="op">*</span>n0
[<span class="dv">1</span>] <span class="fl">40.78049</span></code></pre></div>
<p>Tolkningen av resultaten kan skrivas på olika sätt. Nedan är två alternativ:</p>
<ul>
<li>Bland högutbildade röker 22 procentenheter mindre jämfört med lågutbildade. Med 95% säkerhet finns mellan 34 och 11 procenheter mindre rökare bland högutbildade jämfört med lågutbildade.<br />
</li>
<li>Skillnaden i andelen som röker bland högutbildade jämfört med lågutbildade är -0.22 (95% KI: -0.33; -11%).</li>
</ul>
<p>Litar vi på resultaten? Detta bygger på två förutsättningar, OSU (som vi vet från designen) samt att normalapproximationen (vilket vi undersöker i stickprovet) fungerar. Bägge försättningarna är uppfyllda!</p>
<p>Anta att syftet inte är att skatta skillnaden i andelen som röker, utan att frågan snarare är huruvida man röker i samma utsträckning oavsett utbildningsnivå. Då kan vi istället genomföra hypotesprövning och testa <span class="math inline">\(H_0: p_1 = p_0\)</span> mot en två-sidig mothypotes, <span class="math inline">\(H_0: p_1 \neq p_0\)</span> andvänds test-funktionen <span class="math display">\[ z = \dfrac{\hat{p}_1 - \hat{p}_0}{\hat{p}_{pool}(1- \hat{p}_{pool})\left(\dfrac{1}{n_1} + \dfrac{1}{n_0}\right)}\]</span> där <span class="math display">\[\hat{p}_{pool} = \dfrac{n_1\hat{p}_1 + n_0 \hat{p}_0}{n_1 + n_0}\]</span>. Testfunktionen är <span class="math inline">\(N(0,1)\)</span> om nollhypotesen är sann om vi har OSU och om normalapproximation gäller (<span class="math inline">\(n_1p_1(1-p_1) &gt; 5\)</span> och <span class="math inline">\(n_0p_0(1-p_0) &gt; 5\)</span>).</p>
<p>Nedan jämförs två likvärdiga alternativ att i R genomföra ovanstående test av andelar. Det första alternativet är att använda <strong>prop.test()</strong>. Funktionen används på samma sätt som för konfidensintervall och vi använder därför resultatet från förut.</p>
<p>Det andra alternativet är att implementera formeln ovan och beräkna <span class="math inline">\(p\)</span>-värdet.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Version 1 (hämta resultat från prop.test())</span>
resultat

    <span class="dv">2</span><span class="op">-</span>sample test <span class="cf">for</span> equality of proportions without continuity
    correction

data<span class="op">:</span><span class="st">  </span><span class="kw">c</span>(x1, x0) out of <span class="kw">c</span>(n1, n0)
X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">14.095</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value =<span class="st"> </span><span class="fl">0.0001738</span>
alternative hypothesis<span class="op">:</span><span class="st"> </span>two.sided
<span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="st"> </span><span class="op">-</span><span class="fl">0.3398732</span> <span class="op">-</span><span class="fl">0.1126079</span>
sample estimates<span class="op">:</span>
<span class="st">   </span>prop <span class="dv">1</span>    prop <span class="dv">2</span> 
<span class="fl">0.3103448</span> <span class="fl">0.5365854</span> 
resultat<span class="op">$</span>p.value
[<span class="dv">1</span>] <span class="fl">0.0001738371</span>

<span class="co"># Version 2</span>
pooled_phat &lt;-<span class="st"> </span>(n1<span class="op">*</span>phat1 <span class="op">+</span><span class="st"> </span>n0<span class="op">*</span>phat0)<span class="op">/</span>(n1 <span class="op">+</span><span class="st"> </span>n0)
z &lt;-<span class="st"> </span>(phat1 <span class="op">-</span><span class="st"> </span>phat0)<span class="op">/</span><span class="kw">sqrt</span>(pooled_phat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pooled_phat)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n0))
p_value &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="kw">abs</span>(z)))
p_value
[<span class="dv">1</span>] <span class="fl">0.0001738371</span></code></pre></div>
<p>De två <span class="math inline">\(p\)</span>-värden är samma och tolkas som att <em>givet att andelen rökare är lika stor i bägge utbildningskategorier i populationen så är det 0.0002 sannolikhet att hitta en så stor skillnad i andelar eller större som vi erhållit</em>. Data stämmer alltså inte alls väl överens med nollhypotesen om ingen skillnad!</p>
<p>Det går även att genomföra en ensidig hypotesprövning. Anta att vi vill testa <span class="math inline">\(H_0: p_0 = p_1\)</span> vs <span class="math inline">\(H_1: p_1 &lt; p_0\)</span>, dvs om andelen rökare mindre bland högutbildade än bland lågutbildade. Vi måste nu <strong>prop.test()</strong> ange att mothypotesen är mindre än. För testet baserat på formeln ändras inte <span class="math inline">\(z\)</span>-värdet, däremot hur <span class="math inline">\(p\)</span>-värdet beräknas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Version 1</span>
resultat_less &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="kw">c</span>(x1, x0), <span class="kw">c</span>(n1, n0), <span class="dt">alternativ =</span> <span class="st">&quot;less&quot;</span>, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
resultat_less

    <span class="dv">2</span><span class="op">-</span>sample test <span class="cf">for</span> equality of proportions without continuity
    correction

data<span class="op">:</span><span class="st">  </span><span class="kw">c</span>(x1, x0) out of <span class="kw">c</span>(n1, n0)
X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">14.095</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value =<span class="st"> </span><span class="fl">8.692e-05</span>
alternative hypothesis<span class="op">:</span><span class="st"> </span>less
<span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="st"> </span><span class="op">-</span><span class="fl">1.000000</span> <span class="op">-</span><span class="fl">0.130877</span>
sample estimates<span class="op">:</span>
<span class="st">   </span>prop <span class="dv">1</span>    prop <span class="dv">2</span> 
<span class="fl">0.3103448</span> <span class="fl">0.5365854</span> 

<span class="co"># Version 2</span>
<span class="kw">pnorm</span>(z)
[<span class="dv">1</span>] <span class="fl">8.691855e-05</span></code></pre></div>
<p>Vi får ett mycket lågt <span class="math inline">\(p\)</span>-värde (<span class="math inline">\(p&lt;0.001\)</span>) som säger oss att <em>givet att andelen rökare är lika stor i bägge utbildningskategorier i populationen så är det 0.00008 sannolikhet att finna att högutbildade röker i så mycket mindre utsträckning eller ännu mindre jämfört med lågutbildade.</em> Data stämmer alltså inte alls väl överens med nollhypotesen om ingen skillnad!</p>
<p>Ett annat sätt att generellt testa samband mellan binära variabler är att genomföra <em>test för oberoende</em>. En vanlig meted för att testa detta är <span class="math inline">\(\chi^2\)</span>-metoden, som testar hypoteserna:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Det finns inget samband mellan variablerna (oberoende)</li>
<li><span class="math inline">\(H_1\)</span>: Det finns ett samband mellan variablerna (beroende)</li>
</ul>
<p>Notera att mothypotesens riktning är ospecificerad! För att genomföra ett <span class="math inline">\(\chi^2\)</span>-test används test-statistikan</p>
<p><span class="math display">\[\chi^2 = \dfrac{\sum_{i=1}^r\sum_{j=1}^k\left(O_{ij} - E_{ij}\right)^2}{E_{ij}},\]</span> vilken är <span class="math inline">\(\chi^2\)</span>-fördelad med <span class="math inline">\((r-1)(k-1)\)</span> frihetsgrader, där <span class="math inline">\(r\)</span> är antal rader och <span class="math inline">\(k\)</span> är antal kolumner i tabellen.</p>
<p>För att implementera testet i R används i regel <strong>chisq.test()</strong> på ett tabell-objekt. Nedan illustreras också hur man genom att tillämpa formeln ovan kan genomföra ett <span class="math inline">\(\chi^2\)</span>-test. Det framräknade <span class="math inline">\(\chi^2\)</span>-värdet används sedan i <strong>pchisq()</strong> för ett erhålla <span class="math inline">\(p\)</span>-värdet.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Version 1. Använder ej kontinuitetskorrekation eftersom </span>
 resultat_chisq &lt;-<span class="st"> </span><span class="kw">chisq.test</span>( freq_table_edu_smoke, <span class="dt">correct =</span> <span class="ot">FALSE</span> )
 resultat_chisq

    Pearson<span class="st">&#39;s Chi-squared test</span>

<span class="st">data:  freq_table_edu_smoke</span>
<span class="st">X-squared = 14.095, df = 1, p-value = 0.0001738</span>

<span class="st"># Version 2</span>
<span class="st"># Observerade frekvenser</span>
<span class="st">Oij &lt;- freq_table_edu_smoke</span>
<span class="st">full_table &lt;- addmargins(Oij)</span>

<span class="st"># Beräkna förväntade frekvenser och skapa en matris Eij med sådana</span>
<span class="st">totalsumma &lt;- full_table[3,3]</span>
<span class="st">radsummor &lt;- full_table[3, c(1,2)]</span>
<span class="st">kolsummor &lt;- full_table[c(1,2), 3]</span>
<span class="st">Eij &lt;- matrix(NA, 2, 2)</span>
<span class="st">Eij[1,1] &lt;- kolsummor[1]*radsummor[1]/totalsumma</span>
<span class="st">Eij[2,1] &lt;- kolsummor[2]*radsummor[1]/totalsumma</span>
<span class="st">Eij[1,2] &lt;- kolsummor[1]*radsummor[2]/totalsumma</span>
<span class="st">Eij[2,2] &lt;- kolsummor[2]*radsummor[2]/totalsumma</span>

<span class="st"># Beräkna teststatistikan</span>
<span class="st">X2obs &lt;- sum( (Oij - Eij)^2/Eij )</span>
<span class="st">fg &lt;- (dim(Eij)[1] - 1)*(dim(Eij)[2] - 1)     #(r-1)*(k-1) frihetsgrader</span>

<span class="st">## pchisq ger vänstersvanssannolikhet i en chitvå-fördelning med df- frihetsgrader</span>
<span class="st"> p_value &lt;- 1 - pchisq(X2obs, df = fg)  </span>
<span class="st"> p_value</span>
<span class="st">[1] 0.0001738371</span>
<span class="st"> </span>
<span class="st"># Undersök förutsättningarna. Med any() kan vi kolla om något element i matrisen är mindre än 5</span>
<span class="st">check_assumptions &lt;- any(Eij &lt; 5)</span>
<span class="st">check_assumptions</span>
<span class="st">[1] FALSE</span></code></pre></div>
<p>Vi erhåller samma <span class="math inline">\(p\)</span>-värde som när vi testade för skillnad av andelar i fallet med två-sidig mothypotes. <span class="math inline">\(\chi^2\)</span>-metoden kan alltså användas för att testa andelar, men testet är också ett mer generellt test för oberoende. Om två binära varaiabler är beroende, så är de beroende oavsett val av effektstorlek, eärför kan vi använda <span class="math inline">\(\chi^2\)</span>-metoden även för <span class="math inline">\(p_{kvot}\)</span> och <span class="math inline">\(OR\)</span>.</p>
</div>
<div id="övningar-3" class="section level2">
<h2><span class="header-section-number">5.10</span> Övningar</h2>
<div id="övning-5.1" class="section level3 unnumbered">
<h3>Övning 5.1</h3>
<p>En undersökning ville testa jämföra andelen vänsterhänta bland män och kvinnor. I studien drogs ett OSU av med 30 kvinnor varav 6 var vänsterhänta samt ett OSU med 29 män varav 4 är vänsterhänta. Är andelen vänsterhänta mellan kvinnor och män samma? Redovisa p-värdet som du erhåller från ett test av nollhypotesen. Tolka resultatet.</p>
<button title="q501" type="button" onclick="if(document.getElementById('q501') .style.display=='none')
              {document.getElementById('q501') .style.display=''}
            else{document.getElementById('q501') .style.display='none'}">
Visa svar
</button>
<div id="q501" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
 x_f &lt;-<span class="st"> </span><span class="dv">6</span>
 n_f &lt;-<span class="st"> </span><span class="dv">30</span>
 x_m &lt;-<span class="st"> </span><span class="dv">4</span>
 n_m&lt;-<span class="st"> </span><span class="dv">29</span>
 <span class="kw">prop.test</span>(<span class="kw">c</span>(x_f,x_m), <span class="kw">c</span>(n_f, n_m), <span class="dt">correct =</span> <span class="ot">FALSE</span>) 
<span class="op">&gt;</span><span class="st"> </span>Warning <span class="cf">in</span> <span class="kw">prop.test</span>(<span class="kw">c</span>(x_f, x_m), <span class="kw">c</span>(n_f, n_m), <span class="dt">correct =</span> <span class="ot">FALSE</span>)<span class="op">:</span><span class="st"> </span>Chi<span class="op">-</span>
<span class="er">&gt;</span><span class="st"> </span>squared approximation may be incorrect
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">   </span><span class="dv">2</span><span class="op">-</span>sample test <span class="cf">for</span> equality of proportions without continuity
<span class="op">&gt;</span><span class="st">   </span>correction
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st"> </span>data<span class="op">:</span><span class="st">  </span><span class="kw">c</span>(x_f, x_m) out of <span class="kw">c</span>(n_f, n_m)
<span class="op">&gt;</span><span class="st"> </span>X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">0.40357</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value =<span class="st"> </span><span class="fl">0.5252</span>
<span class="op">&gt;</span><span class="st"> </span>alternative hypothesis<span class="op">:</span><span class="st"> </span>two.sided
<span class="op">&gt;</span><span class="st"> </span><span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="er">&gt;</span><span class="st">  </span><span class="op">-</span><span class="fl">0.1282953</span>  <span class="fl">0.2524333</span>
<span class="op">&gt;</span><span class="st"> </span>sample estimates<span class="op">:</span>
<span class="er">&gt;</span><span class="st">   </span>prop <span class="dv">1</span>   prop <span class="dv">2</span> 
<span class="op">&gt;</span><span class="st"> </span><span class="fl">0.200000</span> <span class="fl">0.137931</span>

<span class="co"># Undersök om de förväntade frekvenserna är större än 5 i alla celler</span>
 freq_table &lt;-<span class="st"> </span><span class="kw">as.table</span>( <span class="kw">matrix</span>( <span class="kw">c</span>(<span class="dv">6</span>, <span class="dv">24</span>, <span class="dv">4</span>, <span class="dv">25</span>), <span class="dv">2</span>, <span class="dv">2</span>) )
 test &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(freq_table, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
<span class="op">&gt;</span><span class="st"> </span>Warning <span class="cf">in</span> <span class="kw">chisq.test</span>(freq_table, <span class="dt">correct =</span> <span class="ot">FALSE</span>)<span class="op">:</span><span class="st"> </span>Chi<span class="op">-</span>squared
<span class="op">&gt;</span><span class="st"> </span>approximation may be incorrect
 test
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">   </span>Pearson<span class="st">&#39;s Chi-squared test</span>
<span class="st">&gt; </span>
<span class="st">&gt; data:  freq_table</span>
<span class="st">&gt; X-squared = 0.40357, df = 1, p-value = 0.5252</span>
<span class="st"> test$expected</span>
<span class="st">&gt;           A         B</span>
<span class="st">&gt; A  5.084746  4.915254</span>
<span class="st">&gt; B 24.915254 24.084746</span></code></pre></div>
<p><span class="math inline">\(\chi^2\)</span>-testet går alltså inte att använda! Förutsättningen om förväntade frekvenser större än 5 i alla celler är inte uppfylld. Det finns alternativa test som Fishers exakta test, men dessa ingår inte på kursen.</p>
</div>
</div>
<p></br></p>
</div>
<div id="övning-5.2" class="section level3 unnumbered">
<h3>Övning 5.2</h3>
<p>Raghubir &amp; Srivastava (2009) undersökte effekten av storleken på sedlar och mynt på i vilken utsträckning pengarna används. Ett experiment genomfördes där 46 studenter fick en endollarssedel och 43 stycken studenter fick 4 stycken amerikanska 25 cents mynt, så kallade quarters. Studenterna fick sedan välja mellan att spara pengarna eller spendera dem på tuggummi och mintpastiller.</p>
<p>Nedan redovisas en sammanfattning av studien.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">1 dollar sedel</th>
<th align="center">4 quarters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spenderade pengarna</td>
<td align="center">12</td>
<td align="center">27</td>
</tr>
<tr class="even">
<td>Sparade pengarna</td>
<td align="center">34</td>
<td align="center">16</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li><p>Skapa en tabell som deskriptivt redovisar sambandet</p></li>
<li><p>Skapa en figur som deskriptivt redovisar sambandet</p></li>
<li><p>Skatta skillnaden i andelar som spenderar pengar tillsammans med tillhörande 90% konfidensintervall.</p></li>
<li><p>Beräkna <span class="math inline">\(p\)</span>-värdet om givet att det inte finns någon skillnad mellan grupperna vad gäller andelen som spenderar pengarna.</p></li>
<li><p>Ge en utförlig tolkning av resultaten.</p></li>
<li><p>Litar du på resultaten? Är förutsättningarna uppfyllda?</p></li>
</ol>
<button title="q502" type="button" onclick="if(document.getElementById('q502') .style.display=='none')
              {document.getElementById('q502') .style.display=''}
            else{document.getElementById('q502') .style.display='none'}">
Visa svar
</button>
<div id="q502" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
<span class="co"># a)</span>
 freq_table &lt;-<span class="st"> </span><span class="kw">as.table</span>( <span class="kw">matrix</span>( <span class="kw">c</span>(<span class="dv">12</span>, <span class="dv">34</span>, <span class="dv">27</span>, <span class="dv">16</span>), <span class="dv">2</span>, <span class="dv">2</span>))
 <span class="kw">colnames</span>(freq_table) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;1 endollarsedel&quot;</span>, <span class="st">&quot;4 quarters&quot;</span>)
 <span class="kw">rownames</span>(freq_table) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Spenderade pengarna&quot;</span>, <span class="st">&quot;Sparade pengarna&quot;</span>)
 prop_table &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table, <span class="dv">2</span>)
 table_bill_spending &lt;-<span class="st"> </span><span class="kw">cbind</span>(freq_table[,<span class="dv">1</span>], <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>prop_table[,<span class="dv">1</span>], <span class="dv">1</span>),
                             freq_table[,<span class="dv">2</span>], <span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>prop_table[,<span class="dv">2</span>], <span class="dv">1</span>))
 <span class="kw">colnames</span>(table_bill_spending) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;1 endollarsedel (n)&quot;</span>, <span class="st">&quot;1 dollarsedel (%)&quot;</span>, <span class="st">&quot;4 quarters (n)&quot;</span>, <span class="st">&quot;4 quarters  (%)&quot;</span>)
 <span class="kw">rownames</span>(table_bill_spending) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Spenderade pengarna&quot;</span>, <span class="st">&quot;Sparade pengarna&quot;</span>)
 table_bill_spending
                    <span class="dv">1</span> <span class="kw">endollarsedel</span> (n) <span class="dv">1</span> <span class="kw">dollarsedel</span> (%) <span class="dv">4</span> <span class="kw">quarters</span> (n)
Spenderade pengarna                  <span class="dv">12</span>              <span class="fl">26.1</span>             <span class="dv">27</span>
Sparade pengarna                     <span class="dv">34</span>              <span class="fl">73.9</span>             <span class="dv">16</span>
                    <span class="dv">4</span> <span class="kw">quarters</span>  (%)
Spenderade pengarna            <span class="fl">62.8</span>
Sparade pengarna               <span class="fl">37.2</span>
 
<span class="co"># b)</span>
 percentages_spending&lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">100</span><span class="op">*</span>prop_table[<span class="dv">1</span>,], <span class="dv">1</span>)
 my_bar &lt;-<span class="st"> </span><span class="kw">barplot</span>(  percentages_spending, 
                     <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;1 dollarsedel&quot;</span>, <span class="st">&quot;4 quarters&quot;</span>), 
                     <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">80</span>), 
                     <span class="dt">col =</span> <span class="st">&quot;lightblue&quot;</span>,
                     <span class="dt">border =</span> <span class="st">&quot;lightblue&quot;</span>,
                     <span class="dt">ylab =</span> <span class="st">&quot;Spenderade pengarna (%)&quot;</span>)
 <span class="kw">text</span>(<span class="dt">x =</span> my_bar, <span class="dt">y =</span> percentages_spending <span class="op">+</span><span class="st"> </span><span class="dv">6</span>, 
     <span class="dt">labels =</span> <span class="kw">paste</span>(percentages_spending, <span class="st">&quot;%&quot;</span>,  <span class="dt">sep=</span><span class="st">&quot;&quot;</span>)) </code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-198-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">
<span class="co"># c) </span>
<span class="co"># Version 1</span>
 x1 &lt;-<span class="st"> </span>freq_table[<span class="dv">1</span>,<span class="dv">1</span>]
 x0 &lt;-<span class="st"> </span>freq_table[<span class="dv">1</span>,<span class="dv">2</span>]
 n1 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table[,<span class="dv">1</span>])
 n0 &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table[,<span class="dv">2</span>])
 resultat &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="kw">c</span>(x1, x0), <span class="kw">c</span>(n1, n0), <span class="dt">conf.level =</span> <span class="fl">0.9</span>, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
 p_differens &lt;-<span class="st"> </span>resultat<span class="op">$</span>estimate[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>resultat<span class="op">$</span>estimate[<span class="dv">2</span>]
 p_differens_KI &lt;-<span class="st"> </span>resultat<span class="op">$</span>conf.int
 p_differens
    prop <span class="dv">1</span> 
<span class="op">-</span><span class="fl">0.3670374</span> 
 p_differens_KI
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.5284105</span> <span class="op">-</span><span class="fl">0.2056644</span>
<span class="kw">attr</span>(,<span class="st">&quot;conf.level&quot;</span>)
[<span class="dv">1</span>] <span class="fl">0.9</span>

<span class="co"># Version 2</span>
 p1hat &lt;-<span class="st"> </span>x1<span class="op">/</span>n1
 p0hat &lt;-<span class="st"> </span>x0<span class="op">/</span>n0
 p_diff &lt;-<span class="st"> </span>p1hat <span class="op">-</span><span class="st"> </span>p0hat
 vp_diff &lt;-<span class="st"> </span>p1hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p1hat)<span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span>p0hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p0hat)<span class="op">/</span>n0
 alpha &lt;-<span class="st"> </span><span class="fl">0.1</span>
 z_alpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha<span class="op">/</span><span class="dv">2</span>)
 ll &lt;-<span class="st"> </span>p_diff <span class="op">-</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vp_diff)
 ul &lt;-<span class="st"> </span>p_diff <span class="op">+</span><span class="st"> </span>z_alpha<span class="op">*</span><span class="kw">sqrt</span>(vp_diff)
 p_diff_KI &lt;-<span class="st"> </span><span class="kw">c</span>(ll, ul)
 p_diff
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.3670374</span>
 p_diff_KI
[<span class="dv">1</span>] <span class="op">-</span><span class="fl">0.5284105</span> <span class="op">-</span><span class="fl">0.2056644</span>
 
<span class="co"># d)</span>
<span class="co"># Version 1</span>
 p_value_p_differens &lt;-<span class="st"> </span>resultat<span class="op">$</span>p.value
 p_value_p_differens
[<span class="dv">1</span>] <span class="fl">0.0004877499</span>

<span class="co"># Version 2</span>
 pooled_phat &lt;-<span class="st"> </span>(n1<span class="op">*</span>p1hat <span class="op">+</span><span class="st"> </span>n0<span class="op">*</span>p0hat)<span class="op">/</span>(n1 <span class="op">+</span><span class="st"> </span>n0)
 zobs &lt;-<span class="st"> </span>(p1hat <span class="op">-</span><span class="st"> </span>p0hat)<span class="op">/</span><span class="kw">sqrt</span>(pooled_phat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pooled_phat)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n0))
 p_value_p_diff &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="kw">abs</span>(zobs)))
 p_value_p_diff
[<span class="dv">1</span>] <span class="fl">0.0004877499</span></code></pre></div>
<ol start="5" style="list-style-type: lower-alpha">
<li><p>Se formuleringar ovan om andelar, differens av andelar, KI och p-värde.</p></li>
<li><p>OSU (experiment) och normalapproximation gäller. Jag litar på resultaten.</p></li>
</ol>
</div>
</div>
<p></br></p>
</div>
<div id="övning-5.3" class="section level3 unnumbered">
<h3>Övning 5.3</h3>
<p>Rosa et al. (1998) undersökte om en typ av ‘’healers’’ hade förmåga att känna mänskliga kroppars så kallade energifält. Forskarna besökte en mässa för alternativmedicin och gjorde där ett experiment som gick ut på att healers skulle identifiera om undersökarens vänstra eller högre hand var närmst healern. Händerna var dolda under ett tygstycke. Totalt genomfördes 130 försök och av dessa lyckades healers identifera rätt hand 53 gånger. Undersök det finns belägg för denna förmåga bland healers.</p>
<p>Tolka resultatet!</p>
<button title="q503" type="button" onclick="if(document.getElementById('q503') .style.display=='none')
              {document.getElementById('q503') .style.display=''}
            else{document.getElementById('q503') .style.display='none'}">
Visa svar
</button>
<div id="q503" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
<span class="co"># Version 1</span>
 x &lt;-<span class="st"> </span><span class="dv">53</span>
 n &lt;-<span class="st"> </span><span class="dv">130</span>
 resultat &lt;-<span class="st">  </span><span class="kw">prop.test</span>(<span class="dv">53</span>, <span class="dv">130</span>, <span class="dt">p =</span> <span class="fl">0.5</span>, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
 p_value &lt;-<span class="st"> </span>resultat<span class="op">$</span>p.value
 p_value 
[<span class="dv">1</span>] <span class="fl">0.0352966</span>
 
<span class="co"># Version 2</span>
phat &lt;-<span class="st"> </span>x<span class="op">/</span>n
pH0 &lt;-<span class="st"> </span><span class="fl">0.5</span>
z &lt;-<span class="st"> </span>(phat <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span>)<span class="op">/</span><span class="kw">sqrt</span>(pH0<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pH0)<span class="op">/</span>n)
p_value_v2 &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="kw">pnorm</span>(z)
p_value_v2
[<span class="dv">1</span>] <span class="fl">0.0352966</span></code></pre></div>
<p>Givet att healers inte är bättre än slumpen, dvs <span class="math inline">\(H_0: p = 0.5\)</span>, så är sannolikheten <span class="math inline">\(p=0.035\)</span> att observera ett så extremt värde som det studien ger. Hur tolkar vi detta rent praktiskt?</p>
<ol style="list-style-type: decimal">
<li><p>För det första ser vi att om det vore så att det skulle finnas en förmåga så verkar det snarare vara i negativ riktning, dvs att healers presterar sämre än slumpen.</p></li>
<li><p>För det andra är detta ett exempel på hur man inte ska förlita sig på enskilda studier och hypotesprövning allena. <span class="math inline">\(p\)</span>-värdet är inte särskilt lågt och det är rimligt att tro att resultat helt enkelt är ett slumpfynd och att healers presterar varken bättre eller sämre än slumpen.</p></li>
</ol>
</div>
</div>
<p></br></p>
</div>
<div id="övning-5.4" class="section level3 unnumbered">
<h3>Övning 5.4</h3>
<p>Gerritsen et al. (1998) ville jämföra kiurgi med spjälning av handleden för att hantera det som kallas karpaltunnelsyndrom, dvs smärta till följd av att nerver kläms i handleden. Du erhåller följande datamaterial från studien.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">treatment =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;splint&quot;</span>, <span class="dv">60</span>), <span class="kw">rep</span>(<span class="st">&quot;splint&quot;</span>, <span class="dv">23</span>), <span class="kw">rep</span>(<span class="st">&quot;surgery&quot;</span>, <span class="dv">67</span>), <span class="kw">rep</span>(<span class="st">&quot;surgery&quot;</span>, <span class="dv">6</span>)), 
                 <span class="dt">y =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;succesful&quot;</span>, <span class="dv">60</span>), <span class="kw">rep</span>(<span class="st">&quot;unsucsessful&quot;</span>,<span class="dv">23</span>), <span class="kw">rep</span>(<span class="st">&quot;succesful&quot;</span>, <span class="dv">67</span>), <span class="kw">rep</span>(<span class="st">&quot;unsucsessful&quot;</span>,<span class="dv">6</span>)))</code></pre></div>
<p>Undersökarna vill beräkna kvoten av andelar lyckade behandlingar (relativ risk), där spjälning är referensgrupp. Eftersom forskarna vill fatta beslut vill man att en hypotesprövning genomförs på 5% signifikansnivå.</p>
<button title="q504" type="button" onclick="if(document.getElementById('q504') .style.display=='none')
              {document.getElementById('q504') .style.display=''}
            else{document.getElementById('q504') .style.display='none'}">
Visa svar
</button>
<div id="q504" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
 df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">treatment =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;splint&quot;</span>, <span class="dv">60</span>), <span class="kw">rep</span>(<span class="st">&quot;splint&quot;</span>, <span class="dv">23</span>), <span class="kw">rep</span>(<span class="st">&quot;surgery&quot;</span>, <span class="dv">67</span>),  <span class="kw">rep</span>(<span class="st">&quot;surgery&quot;</span>, <span class="dv">6</span>)), 
                 <span class="dt">y =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;succesful&quot;</span>, <span class="dv">60</span>), <span class="kw">rep</span>(<span class="st">&quot;unsucsessful&quot;</span>,<span class="dv">23</span>), <span class="kw">rep</span>(<span class="st">&quot;succesful&quot;</span>, <span class="dv">67</span>),   <span class="kw">rep</span>(<span class="st">&quot;unsucsessful&quot;</span>,<span class="dv">6</span>)))
 freq_table &lt;-<span class="st"> </span><span class="kw">table</span>(df<span class="op">$</span>y, df<span class="op">$</span>treatment)
 prop_table &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table, <span class="dv">2</span>) 
 phat_splint &lt;-<span class="st"> </span>prop_table[<span class="dv">1</span>,<span class="dv">1</span>]
 phat_surgery &lt;-<span class="st"> </span>prop_table[<span class="dv">1</span>,<span class="dv">2</span>]
 p_kvot &lt;-<span class="st"> </span>phat_surgery<span class="op">/</span>phat_splint 
 resultat &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(freq_table, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
 p_kvot
[<span class="dv">1</span>] <span class="fl">1.269635</span>
 resultat<span class="op">$</span>p.value
[<span class="dv">1</span>] <span class="fl">0.001792853</span></code></pre></div>
<p>En patient har 27% (p = 0.002) större chans till lyckad behandling om patienten genomgår kirurgi istället för behandling. Eftersom <span class="math inline">\(p&lt;0.05\)</span> förkastar vi på 5% signifikansnivå nollhypotesen om att kirurgi och spjälning är lika effektiva.</p>
</div>
</div>
<p></br></p>
</div>
<div id="övning-5.5" class="section level3 unnumbered">
<h3>Övning 5.5</h3>
<p>En sjuksköterska är anklagad för att ha mördat ett antal patienter. Som bevis jämför man dödligheten på skift där den anklagade har arbetat med skift där den anklagade inte har arbetat. Anta nu att du är domare i det aktuella fallet. Ladda in nedanstående tabell. Ställ upp en nollhypotes och analysera data och bilda dig en uppfattning om den anklagade är oskyldig.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">accused &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;accused was working&quot;</span>, <span class="dv">40</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was working&quot;</span>, <span class="dv">217</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was not working&quot;</span>, <span class="dv">34</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was not working&quot;</span>, <span class="dv">1350</span>)) 
death &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;shifts with a death&quot;</span>, <span class="dv">40</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts without a death&quot;</span>,<span class="dv">217</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts with a death&quot;</span>, <span class="dv">34</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts without a death&quot;</span>, <span class="dv">1350</span>))
<span class="kw">table</span>(accused, death)</code></pre></div>
<button title="q505" type="button" onclick="if(document.getElementById('q505') .style.display=='none')
              {document.getElementById('q505') .style.display=''}
            else{document.getElementById('q505') .style.display='none'}">
Visa svar
</button>
<div id="q505" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
accused &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;accused was working&quot;</span>, <span class="dv">40</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was working&quot;</span>, <span class="dv">217</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was not working&quot;</span>, <span class="dv">34</span>), 
             <span class="kw">rep</span>(<span class="st">&quot;accused was not working&quot;</span>, <span class="dv">1350</span>)) 
death &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;shifts with a death&quot;</span>, <span class="dv">40</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts without a death&quot;</span>,<span class="dv">217</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts with a death&quot;</span>, <span class="dv">34</span>), 
           <span class="kw">rep</span>(<span class="st">&quot;shifts without a death&quot;</span>, <span class="dv">1350</span>))
freq_table &lt;-<span class="st"> </span><span class="kw">table</span>(accused, death)
freq_table
                         death
accused                   shifts with a death shifts without a death
  accused was not working                  <span class="dv">34</span>                   <span class="dv">1350</span>
  accused was working                      <span class="dv">40</span>                    <span class="dv">217</span>
resultat &lt;-<span class="st"> </span><span class="kw">chisq.test</span>(freq_table)
resultat<span class="op">$</span>p.value
[<span class="dv">1</span>] <span class="fl">6.489411e-20</span></code></pre></div>
<p>Givet att det finns det inte skiljer sig åt mellan den anklagades skift och andras skift är det mycket liten sannolikhet att observera så många döda som vi observerar eller mer extremt ($p &lt; 0.001).</p>
<p>Kristen Gilbert var en amerikansk sjuksköterska som fick smeknamnet “Angel Death” efter ett antal misstänkta dödsfall på psykiatriska avdelningar där hon arbetade. Hon blev så småningom dömd för mord och avtjänar numera livstids fängelsestraff utan möjlighet till benådning.</p>
<p>Det är mycket viktigt att komma ihåg vad en jämförelse innebär.</p>
<ul>
<li>Ett litet <span class="math inline">\(p\)</span>-värde tyder på något avvikande</li>
<li>Ett litet <span class="math inline">\(p\)</span>-värde talar inte om VARFÖR det avviken. För detta krävs antaganden. Till exempel randomiserades inte Gilbert till avdelningarna. Låt säg att ventilationen på hennes skift alltid var sämre, med högre partikelhalter. Då skulle detta vara orsaken. För att vara säker på att det är Gilbert som orsakat dödsfallen krävs att vissa förutsättningar är uppfyllda, t ex att skiften är slumpmässigt tilldelade. Domstolen beaktade därför inte statistiken som bevis. Vad som skedde var dock att statistiken avslöjade ett mönster som gjorde att man undersökte fallen ytterligare och därför kunde gripa Gilbert.</li>
</ul>
<p>Den intresserade kan läsa här om hur statistiken användes i just detta fall: <a href="http://www.stat.ucla.edu/~nchristo/statistics100B/article.pdf" class="uri">http://www.stat.ucla.edu/~nchristo/statistics100B/article.pdf</a></p>
</div>
</div>
<p></br></p>
</div>
<div id="övning-5.6" class="section level3 unnumbered">
<h3>Övning 5.6</h3>
<p>En studie 1980 undersökte homosexuellas situation Sverige. En del av denna studie utgjordes bland annat en enkätundersökning. Ladda ner Lilla Enkäten som är txt-fil som finns i zip-filen “Enkäterna i csv-format” på <a href="https://riksarkivet.se/psidata/livet-som-gay" class="uri">https://riksarkivet.se/psidata/livet-som-gay</a>. Utgå från att data är insamlat med OSU och besvara sedan följande frågor:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Har den svarande själv talat om för någon heterosexuell bekant (som inte bara är arbetskamrat) att den svarande är homo/bisexuell? Variabeln heter <em>TALAT_OM</em>.</p></li>
<li><p>Finns ett samband mellan kön (<strong>KOEN</strong>) och fråga a)?</p></li>
<li><p>Undersök samband mellan att känna skam eller ångest (<strong>SKAM</strong>) och <em>TALAT_OM</em>? Redovisa bortfall. Redovisa en figur.</p></li>
</ol>
<button title="q506" type="button" onclick="if(document.getElementById('q506') .style.display=='none')
              {document.getElementById('q506') .style.display=''}
            else{document.getElementById('q506') .style.display='none'}">
Visa svar
</button>
<div id="q506" style="display:none">
<div class="alert alert-info">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())
 df &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&quot;data/Lilla_enkaeten.txt&quot;</span>)

<span class="co"># Undersök variabeln och variabelkategorierna</span>
 <span class="kw">summary</span>(df<span class="op">$</span>TALAT_OM)
<span class="op">&gt;</span><span class="st">                  </span>Ja, för en bekant              Ja, för flera bakanta 
<span class="op">&gt;</span><span class="st">                                 </span><span class="dv">92</span>                                <span class="dv">466</span> 
<span class="op">&gt;</span><span class="st"> </span>Jag har inga heterosexuella vänner                                Nej 
<span class="op">&gt;</span><span class="st">                                  </span><span class="dv">8</span>                                <span class="dv">181</span>
 <span class="kw">table</span>(df<span class="op">$</span>TALAT_OM, <span class="dt">useNA =</span> <span class="st">&quot;ifany&quot;</span>)
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">                  </span>Ja, för en bekant              Ja, för flera bakanta 
<span class="op">&gt;</span><span class="st">                                 </span><span class="dv">92</span>                                <span class="dv">466</span> 
<span class="op">&gt;</span><span class="st"> </span>Jag har inga heterosexuella vänner                                Nej 
<span class="op">&gt;</span><span class="st">                                  </span><span class="dv">8</span>                                <span class="dv">181</span>
 
<span class="co"># Skapar en tom variabel och koda sedan alla nej till 1 och övriga till 0</span>
 df<span class="op">$</span>EJ_TALAT_OM_bin &lt;-<span class="st"> </span><span class="ot">NA</span>
 df<span class="op">$</span>EJ_TALAT_OM_bin[df<span class="op">$</span>TALAT_OM <span class="op">==</span><span class="st"> &quot;Ja, för en bekant&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
 df<span class="op">$</span>EJ_TALAT_OM_bin[df<span class="op">$</span>TALAT_OM <span class="op">==</span><span class="st"> &quot;Ja, för flera bakanta&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
 df<span class="op">$</span>EJ_TALAT_OM_bin[df<span class="op">$</span>TALAT_OM <span class="op">==</span><span class="st"> &quot;Jag har inga heterosexuella vänner&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
 df<span class="op">$</span>EJ_TALAT_OM_bin[df<span class="op">$</span>TALAT_OM <span class="op">==</span><span class="st"> &quot;Nej&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span>

<span class="co"># a)    </span>
 freq_table_EJ_TALAT_OM &lt;-<span class="st"> </span><span class="kw">table</span>(df<span class="op">$</span>EJ_TALAT_OM_bin)
 x &lt;-<span class="st"> </span>freq_table_EJ_TALAT_OM[<span class="dv">2</span>]
 n &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_EJ_TALAT_OM)
 resultat_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">prop.test</span>(x, n, <span class="dt">correct =</span> <span class="ot">FALSE</span>)
 resultat_<span class="dv">1</span>
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">   </span><span class="dv">1</span><span class="op">-</span>sample proportions test without continuity correction
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st"> </span>data<span class="op">:</span><span class="st">  </span>x out of n, null probability <span class="fl">0.5</span>
<span class="op">&gt;</span><span class="st"> </span>X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">198.43</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value <span class="op">&lt;</span><span class="st"> </span><span class="fl">2.2e-16</span>
<span class="op">&gt;</span><span class="st"> </span>alternative hypothesis<span class="op">:</span><span class="st"> </span>true p is not equal to <span class="fl">0.5</span>
<span class="op">&gt;</span><span class="st"> </span><span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="er">&gt;</span><span class="st">  </span><span class="fl">0.2129447</span> <span class="fl">0.2742972</span>
<span class="op">&gt;</span><span class="st"> </span>sample estimates<span class="op">:</span>
<span class="er">&gt;</span><span class="st">         </span>p 
<span class="op">&gt;</span><span class="st"> </span><span class="fl">0.2423025</span>
 
<span class="co"># b) </span>
<span class="co"># Undersök variabeln kön</span>
 <span class="kw">summary</span>(df<span class="op">$</span>KOEN)
<span class="op">&gt;</span><span class="st"> </span>Kvinna    Man 
<span class="op">&gt;</span><span class="st">     </span><span class="dv">34</span>    <span class="dv">713</span>
 <span class="kw">table</span>(df<span class="op">$</span>KOEN, <span class="dt">useNA =</span> <span class="st">&quot;ifany&quot;</span>)
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st"> </span>Kvinna    Man 
<span class="op">&gt;</span><span class="st">     </span><span class="dv">34</span>    <span class="dv">713</span>
 
<span class="co"># Skapa en korstabell av kön och ej talat om</span>
 freq_table_KOEN_EJ_TALAT_OM &lt;-<span class="st"> </span><span class="kw">table</span>(df<span class="op">$</span>EJ_TALAT_OM_bin, df<span class="op">$</span>KOEN)
 x1 &lt;-<span class="st"> </span>freq_table_KOEN_EJ_TALAT_OM[<span class="dv">2</span>,<span class="dv">1</span>]
 x0 &lt;-<span class="st"> </span>freq_table_KOEN_EJ_TALAT_OM[<span class="dv">2</span>,<span class="dv">2</span>]
 n1 &lt;-<span class="kw">sum</span>(freq_table_KOEN_EJ_TALAT_OM[,<span class="dv">1</span>])
 n0 &lt;-<span class="kw">sum</span>(freq_table_KOEN_EJ_TALAT_OM[,<span class="dv">2</span>])
 p1hat &lt;-<span class="st"> </span>x1<span class="op">/</span>n1
 p0hat &lt;-<span class="st"> </span>x0<span class="op">/</span>n0
 resultat_KOEN_EJ_TALAT_OM &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="kw">c</span>(x1,x0), <span class="kw">c</span>(n1, n0), <span class="dt">correct =</span> <span class="ot">FALSE</span>)
 resultat_KOEN_EJ_TALAT_OM
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">   </span><span class="dv">2</span><span class="op">-</span>sample test <span class="cf">for</span> equality of proportions without continuity
<span class="op">&gt;</span><span class="st">   </span>correction
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st"> </span>data<span class="op">:</span><span class="st">  </span><span class="kw">c</span>(x1, x0) out of <span class="kw">c</span>(n1, n0)
<span class="op">&gt;</span><span class="st"> </span>X<span class="op">-</span>squared =<span class="st"> </span><span class="fl">3.0149</span>, df =<span class="st"> </span><span class="dv">1</span>, p<span class="op">-</span>value =<span class="st"> </span><span class="fl">0.0825</span>
<span class="op">&gt;</span><span class="st"> </span>alternative hypothesis<span class="op">:</span><span class="st"> </span>two.sided
<span class="op">&gt;</span><span class="st"> </span><span class="dv">95</span> percent confidence interval<span class="op">:</span>
<span class="er">&gt;</span><span class="st">  </span><span class="op">-</span><span class="fl">0.24344443</span> <span class="op">-</span><span class="fl">0.01775514</span>
<span class="op">&gt;</span><span class="st"> </span>sample estimates<span class="op">:</span>
<span class="er">&gt;</span><span class="st">    </span>prop <span class="dv">1</span>    prop <span class="dv">2</span> 
<span class="op">&gt;</span><span class="st"> </span><span class="fl">0.1176471</span> <span class="fl">0.2482468</span>

 <span class="co"># Kolla förutsättningarna</span>
 n1<span class="op">*</span>p1hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p1hat)
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="fl">3.529412</span>
 n0<span class="op">*</span>p0hat<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p0hat)
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="fl">133.0603</span>
 
 <span class="co"># c)  </span>
 <span class="co"># Undersök variabeln</span>
 <span class="kw">summary</span>(df<span class="op">$</span>SKAM)
<span class="op">&gt;</span><span class="st">   </span><span class="dv">9</span>  Ja Nej 
<span class="op">&gt;</span><span class="st">  </span><span class="dv">10</span> <span class="dv">344</span> <span class="dv">393</span>
 <span class="kw">table</span>(df<span class="op">$</span>SKAM, <span class="dt">useNA =</span> <span class="st">&quot;ifany&quot;</span>)
<span class="op">&gt;</span><span class="st"> </span>
<span class="er">&gt;</span><span class="st">   </span><span class="dv">9</span>  Ja Nej 
<span class="op">&gt;</span><span class="st">  </span><span class="dv">10</span> <span class="dv">344</span> <span class="dv">393</span>
 
 <span class="co"># Skapa en korstabell</span>
 df<span class="op">$</span>skam_bin &lt;-<span class="st"> </span><span class="ot">NA</span>
 df<span class="op">$</span>skam_bin[df<span class="op">$</span>SKAM <span class="op">==</span><span class="st"> &quot;Ja&quot;</span>] &lt;-<span class="st"> </span><span class="dv">1</span>
 df<span class="op">$</span>skam_bin[df<span class="op">$</span>SKAM <span class="op">==</span><span class="st"> &quot;Nej&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
 df<span class="op">$</span>skam_bin[df<span class="op">$</span>SKAM <span class="op">==</span><span class="st"> </span><span class="dv">9</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>

 freq_table_ej_talat_om_skam &lt;-<span class="st"> </span><span class="kw">table</span>( df<span class="op">$</span>EJ_TALAT_OM_bin,  df<span class="op">$</span>skam_bin)
 <span class="kw">colnames</span>(freq_table_ej_talat_om_skam) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Ej skam&quot;</span>, <span class="st">&quot;Skam&quot;</span>)
 <span class="kw">rownames</span>(freq_table_ej_talat_om_skam) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Ej talat om&quot;</span>, <span class="st">&quot;Talat om&quot;</span>)
 prop_table_ej_talat_om_skam &lt;-<span class="st"> </span><span class="kw">prop.table</span>(freq_table_ej_talat_om_skam, <span class="dv">2</span>)
 
 <span class="kw">barplot</span>( prop_table_ej_talat_om_skam[<span class="dv">2</span>,], 
         <span class="dt">names.arg =</span> <span class="kw">c</span>(<span class="st">&quot;Ej skam&quot;</span>, <span class="st">&quot;Skam&quot;</span>), 
         <span class="dt">ylab =</span> <span class="st">&quot;Andel som tala om&quot;</span>)</code></pre></div>
<p><img src="dpk_files/figure-html/unnamed-chunk-204-1.png" width="960" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> 
 x1_<span class="dv">2</span> &lt;-<span class="st"> </span>freq_table_ej_talat_om_skam[<span class="dv">2</span>,<span class="dv">2</span>]
 x0_<span class="dv">2</span> &lt;-<span class="st"> </span>freq_table_ej_talat_om_skam[<span class="dv">2</span>,<span class="dv">1</span>]
 n1_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_ej_talat_om_skam[,<span class="dv">2</span>])
 n0_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(freq_table_ej_talat_om_skam[,<span class="dv">1</span>])
 p1hat_<span class="dv">2</span> &lt;-<span class="st"> </span>x1_<span class="dv">2</span><span class="op">/</span>n1_<span class="dv">2</span>
 p0hat_<span class="dv">2</span> &lt;-<span class="st"> </span>x0_<span class="dv">2</span><span class="op">/</span>n0_<span class="dv">2</span>
 p_kvot &lt;-<span class="st"> </span>p1hat_<span class="dv">2</span><span class="op">/</span>p0hat_<span class="dv">2</span>
 p_kvot
<span class="op">&gt;</span><span class="st"> </span>[<span class="dv">1</span>] <span class="fl">0.9877362</span>
 resultat_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="kw">c</span>(x1_<span class="dv">2</span>, x0_<span class="dv">2</span>), <span class="kw">c</span>(n1_<span class="dv">2</span>, n0_<span class="dv">2</span>), <span class="dt">correct =</span> <span class="ot">FALSE</span>)</code></pre></div>
<ol style="list-style-type: lower-alpha">
<li><p>Notera att förutsättningen är ej uppfylld för sambandsanalysen. Vi kan inte lita på testet.</p></li>
<li><p>10 värden är kodade som 9, som förmodligen vet ej eller bortfall. Vi sätter dem som NA. Dessa exkuderas ur analysen.</p></li>
</ol>
</div>
</div>
<p></br></p>
</div>
</div>
<div id="referenser-1" class="section level2">
<h2><span class="header-section-number">5.11</span> Referenser</h2>
<p>Gerritsen, A. A., De Vet, H. C., Scholten, R. J., Bertelsmann, F. W., De Krom, M. C., &amp; Bouter, L. M. (2002). Splinting vs surgery in the treatment of carpal tunnel syndrome: a randomized controlled trial. Jama, 288(10), 1245-1251.</p>
<p>Raghubir, P., &amp; Srivastava, J. (2009). <em>The denomination effect.</em> Journal of Consumer Research, 36(4), 701-713</p>
<p>Rosa, L., Rosa, E., Sarner, L., &amp; Barrett, S. (1998). A close look at therapeutic touch. Jama, 279(13), 1005-1010.</p>

<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

</style>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="läsa-in-och-spara-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="kategorivariabler-uppdateras.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
